import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { Loader2, UploadCloud } from "lucide-react";
import { FormEvent, useState } from "react";
import { toast } from "sonner";
import { labelFor } from "./Common";

const inputClass = "h-10 rounded-lg border-slate-200 bg-white focus:border-teal-600";
const selectClass = "h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none focus:border-teal-600 focus:ring-2 focus:ring-teal-600/15";
const errorMessage = (error: unknown) => error instanceof Error ? error.message : "Une erreur est survenue.";
const channels = ["Email", "Reseaux Sociaux", "SEO-Contenu", "Salon Professionnel", "Webinaire", "Publicite Payante", "Autre"] as const;
const contentTypes = ["Article de Blog", "Post Reseau Social", "Newsletter", "Video", "Autre"] as const;
const assetTypes = ["Plaquette", "Argumentaire", "Etude de Cas", "Presentation", "Visuel", "Autre"] as const;
function Field({ label, children, className = "" }: { label: string; children: React.ReactNode; className?: string }) { return <div className={className}><Label className="mb-2 block text-xs font-semibold text-slate-600">{label}</Label>{children}</div>; }
const nullableNumber = (value: string) => value === "none" ? null : Number(value);

export function CampaignDialog({ open, onOpenChange, initial, users }: { open: boolean; onOpenChange: (open: boolean) => void; initial?: any; users: any[] }) {
  const utils = trpc.useUtils(); const create = trpc.marketing.campaigns.create.useMutation(); const update = trpc.marketing.campaigns.update.useMutation();
  const [form, setForm] = useState({ name: initial?.name || "", channel: initial?.channel || "SEO-Contenu", objective: initial?.objective || "", budget: String(initial?.budget || 0), targetLeads: String(initial?.targetLeads || 0), attributedRevenue: String(initial?.attributedRevenue || 0), startDate: initial?.startDate || "", endDate: initial?.endDate || "", status: initial?.status || "Planifiee", ownerId: String(initial?.ownerId || "none") });
  const submit = async (event: FormEvent) => { event.preventDefault(); try { const payload = { name: form.name, channel: form.channel as typeof channels[number], objective: form.objective || null, budget: Number(form.budget), targetLeads: Number(form.targetLeads), attributedRevenue: Number(form.attributedRevenue), startDate: form.startDate || null, endDate: form.endDate || null, status: form.status as "Planifiee" | "En Cours" | "Terminee", ownerId: nullableNumber(form.ownerId) }; if (initial?.id) await update.mutateAsync({ id: initial.id, ...payload }); else await create.mutateAsync(payload); await Promise.all([utils.marketing.invalidate(), utils.analytics.invalidate()]); toast.success(initial ? "Campagne mise à jour" : "Campagne créée"); onOpenChange(false); } catch (error) { toast.error(errorMessage(error)); } };
  const pending = create.isPending || update.isPending;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{initial ? "Modifier la campagne" : "Nouvelle campagne"}</DialogTitle><DialogDescription>Cadrez le canal, le budget, l’objectif et les résultats attribués.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Nom" className="sm:col-span-2"><Input required minLength={3} value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} className={inputClass} /></Field><Field label="Canal"><select value={form.channel} onChange={e => setForm({ ...form, channel: e.target.value })} className={selectClass}>{channels.map(value => <option key={value} value={value}>{labelFor(value)}</option>)}</select></Field><Field label="Statut"><select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })} className={selectClass}>{["Planifiee", "En Cours", "Terminee"].map(value => <option key={value} value={value}>{labelFor(value)}</option>)}</select></Field><Field label="Budget (€)"><Input required type="number" min="0" value={form.budget} onChange={e => setForm({ ...form, budget: e.target.value })} className={inputClass} /></Field><Field label="Objectif de leads"><Input required type="number" min="0" value={form.targetLeads} onChange={e => setForm({ ...form, targetLeads: e.target.value })} className={inputClass} /></Field><Field label="Revenu attribué (€)"><Input required type="number" min="0" value={form.attributedRevenue} onChange={e => setForm({ ...form, attributedRevenue: e.target.value })} className={inputClass} /></Field><Field label="Responsable"><select value={form.ownerId} onChange={e => setForm({ ...form, ownerId: e.target.value })} className={selectClass}><option value="none">Non assigné</option>{users.map(user => <option key={user.id} value={user.id}>{user.fullName}</option>)}</select></Field><Field label="Début"><Input type="date" value={form.startDate} onChange={e => setForm({ ...form, startDate: e.target.value })} className={inputClass} /></Field><Field label="Fin"><Input type="date" value={form.endDate} onChange={e => setForm({ ...form, endDate: e.target.value })} className={inputClass} /></Field><Field label="Objectif" className="sm:col-span-2"><Textarea value={form.objective} onChange={e => setForm({ ...form, objective: e.target.value })} className="min-h-24" /></Field></div><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Annuler</Button><Button type="submit" disabled={pending}>{pending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}{initial ? "Enregistrer" : "Créer"}</Button></DialogFooter></form></DialogContent></Dialog>;
}

export function ContentDialog({ open, onOpenChange, initial, campaigns, users }: { open: boolean; onOpenChange: (open: boolean) => void; initial?: any; campaigns: any[]; users: any[] }) {
  const utils = trpc.useUtils(); const create = trpc.marketing.content.create.useMutation(); const update = trpc.marketing.content.update.useMutation();
  const [form, setForm] = useState({ campaignId: String(initial?.campaignId || "none"), title: initial?.title || "", contentType: initial?.contentType || "Post Reseau Social", brief: initial?.brief || "", targetAudience: initial?.targetAudience || "", draftContent: initial?.draftContent || "", publishDate: initial?.publishDate || "", publicationUrl: initial?.publicationUrl || "", status: initial?.status || "Idee", assignedTo: String(initial?.assignedTo || "none") });
  const submit = async (event: FormEvent) => { event.preventDefault(); try { const payload = { campaignId: nullableNumber(form.campaignId), title: form.title, contentType: form.contentType as typeof contentTypes[number], brief: form.brief || null, targetAudience: form.targetAudience || null, draftContent: form.draftContent || null, publishDate: form.publishDate || null, publicationUrl: form.publicationUrl || null, status: form.status as "Idee" | "En Redaction" | "Planifie" | "Publie", assignedTo: nullableNumber(form.assignedTo) }; if (initial?.id) await update.mutateAsync({ id: initial.id, ...payload }); else await create.mutateAsync(payload); await utils.marketing.invalidate(); toast.success(initial ? "Contenu mis à jour" : "Contenu planifié"); onOpenChange(false); } catch (error) { toast.error(errorMessage(error)); } };
  const pending = create.isPending || update.isPending;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{initial ? "Modifier le contenu" : "Nouveau contenu"}</DialogTitle><DialogDescription>Préparez le brief, la cible, le brouillon et le statut de publication.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Titre" className="sm:col-span-2"><Input required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} className={inputClass} /></Field><Field label="Campagne"><select value={form.campaignId} onChange={e => setForm({ ...form, campaignId: e.target.value })} className={selectClass}><option value="none">Hors campagne</option>{campaigns.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Type"><select value={form.contentType} onChange={e => setForm({ ...form, contentType: e.target.value })} className={selectClass}>{contentTypes.map(value => <option key={value} value={value}>{labelFor(value)}</option>)}</select></Field><Field label="Statut"><select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })} className={selectClass}>{["Idee", "En Redaction", "Planifie", "Publie"].map(value => <option key={value} value={value}>{labelFor(value)}</option>)}</select></Field><Field label="Date de publication"><Input type="date" value={form.publishDate} onChange={e => setForm({ ...form, publishDate: e.target.value })} className={inputClass} /></Field><Field label="Responsable"><select value={form.assignedTo} onChange={e => setForm({ ...form, assignedTo: e.target.value })} className={selectClass}><option value="none">Non assigné</option>{users.map(user => <option key={user.id} value={user.id}>{user.fullName}</option>)}</select></Field><Field label="Audience cible"><Input value={form.targetAudience} onChange={e => setForm({ ...form, targetAudience: e.target.value })} className={inputClass} /></Field><Field label="Brief" className="sm:col-span-2"><Textarea value={form.brief} onChange={e => setForm({ ...form, brief: e.target.value })} className="min-h-20" /></Field><Field label="Brouillon / texte" className="sm:col-span-2"><Textarea value={form.draftContent} onChange={e => setForm({ ...form, draftContent: e.target.value })} className="min-h-28" /></Field><Field label="URL publiée" className="sm:col-span-2"><Input type="url" value={form.publicationUrl} onChange={e => setForm({ ...form, publicationUrl: e.target.value })} className={inputClass} placeholder="https://…" /></Field></div><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Annuler</Button><Button type="submit" disabled={pending}>{pending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Enregistrer</Button></DialogFooter></form></DialogContent></Dialog>;
}

export function EventDialog({ open, onOpenChange, initial, campaigns }: { open: boolean; onOpenChange: (open: boolean) => void; initial?: any; campaigns: any[] }) {
  const utils = trpc.useUtils(); const create = trpc.marketing.events.create.useMutation(); const update = trpc.marketing.events.update.useMutation();
  const initialDate = initial?.scheduledAt ? new Date(initial.scheduledAt).toISOString().slice(0, 16) : new Date(Date.now() + 7 * 86400000).toISOString().slice(0, 16);
  const [form, setForm] = useState({ campaignId: String(initial?.campaignId || "none"), title: initial?.title || "", eventType: initial?.eventType || "Webinaire", scheduledAt: initialDate, registrationCount: String(initial?.registrationCount || 0), attendeeCount: String(initial?.attendeeCount || 0), meetingsBooked: String(initial?.meetingsBooked || 0), status: initial?.status || "Planifie", meetingUrl: initial?.meetingUrl || "", notes: initial?.notes || "" });
  const submit = async (event: FormEvent) => { event.preventDefault(); try { const payload = { campaignId: nullableNumber(form.campaignId), title: form.title, eventType: form.eventType as "Webinaire" | "Demo Collective" | "Salon" | "Atelier", scheduledAt: new Date(form.scheduledAt), registrationCount: Number(form.registrationCount), attendeeCount: Number(form.attendeeCount), meetingsBooked: Number(form.meetingsBooked), status: form.status as "Planifie" | "Termine" | "Annule", meetingUrl: form.meetingUrl || null, notes: form.notes || null }; if (initial?.id) await update.mutateAsync({ id: initial.id, ...payload }); else await create.mutateAsync(payload); await utils.marketing.invalidate(); toast.success(initial ? "Événement mis à jour" : "Événement créé"); onOpenChange(false); } catch (error) { toast.error(errorMessage(error)); } };
  const pending = create.isPending || update.isPending;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>{initial ? "Modifier l’événement" : "Nouvel événement"}</DialogTitle><DialogDescription>Suivez les inscrits, présents et rendez-vous générés.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Titre" className="sm:col-span-2"><Input required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} className={inputClass} /></Field><Field label="Campagne"><select value={form.campaignId} onChange={e => setForm({ ...form, campaignId: e.target.value })} className={selectClass}><option value="none">Hors campagne</option>{campaigns.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Type"><select value={form.eventType} onChange={e => setForm({ ...form, eventType: e.target.value })} className={selectClass}>{["Webinaire", "Demo Collective", "Salon", "Atelier"].map(value => <option key={value}>{labelFor(value)}</option>)}</select></Field><Field label="Date et heure"><Input required type="datetime-local" value={form.scheduledAt} onChange={e => setForm({ ...form, scheduledAt: e.target.value })} className={inputClass} /></Field><Field label="Statut"><select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })} className={selectClass}>{["Planifie", "Termine", "Annule"].map(value => <option key={value}>{labelFor(value)}</option>)}</select></Field><Field label="Inscrits"><Input type="number" min="0" value={form.registrationCount} onChange={e => setForm({ ...form, registrationCount: e.target.value })} className={inputClass} /></Field><Field label="Présents"><Input type="number" min="0" value={form.attendeeCount} onChange={e => setForm({ ...form, attendeeCount: e.target.value })} className={inputClass} /></Field><Field label="RDV générés"><Input type="number" min="0" value={form.meetingsBooked} onChange={e => setForm({ ...form, meetingsBooked: e.target.value })} className={inputClass} /></Field><Field label="Lien"><Input type="url" value={form.meetingUrl} onChange={e => setForm({ ...form, meetingUrl: e.target.value })} className={inputClass} /></Field><Field label="Notes" className="sm:col-span-2"><Textarea value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} /></Field></div><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Annuler</Button><Button type="submit" disabled={pending}>{pending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Enregistrer</Button></DialogFooter></form></DialogContent></Dialog>;
}

export function LeadDialog({ open, onOpenChange, campaigns }: { open: boolean; onOpenChange: (open: boolean) => void; campaigns: any[] }) {
  const utils = trpc.useUtils(); const mutation = trpc.marketing.leads.create.useMutation();
  const [form, setForm] = useState({ campaignId: "none", fullName: "", email: "", phone: "", jobTitle: "", organizationName: "", organizationType: "Cabinet Liberal", source: "Manuel", consentToContact: true, notes: "" });
  const submit = async (event: FormEvent) => { event.preventDefault(); try { await mutation.mutateAsync({ campaignId: nullableNumber(form.campaignId), fullName: form.fullName, email: form.email, phone: form.phone || null, jobTitle: form.jobTitle || null, organizationName: form.organizationName, organizationType: form.organizationType as "Hopital Public" | "Clinique Privee" | "Groupement Hospitalier" | "Cabinet Liberal", source: form.source as "Site Web" | "Import" | "Evenement" | "Manuel", consentToContact: form.consentToContact, notes: form.notes || null }); await Promise.all([utils.marketing.invalidate(), utils.crm.invalidate()]); toast.success("Lead ajouté et synchronisé au CRM"); onOpenChange(false); } catch (error) { toast.error(errorMessage(error)); } };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[92vh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>Ajouter un lead</DialogTitle><DialogDescription>La fiche Organisation et le Contact seront créés automatiquement dans le CRM si nécessaire.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Nom complet"><Input required value={form.fullName} onChange={e => setForm({ ...form, fullName: e.target.value })} className={inputClass} /></Field><Field label="E-mail"><Input required type="email" value={form.email} onChange={e => setForm({ ...form, email: e.target.value })} className={inputClass} /></Field><Field label="Organisation"><Input required value={form.organizationName} onChange={e => setForm({ ...form, organizationName: e.target.value })} className={inputClass} /></Field><Field label="Type"><select value={form.organizationType} onChange={e => setForm({ ...form, organizationType: e.target.value })} className={selectClass}>{["Hopital Public", "Clinique Privee", "Groupement Hospitalier", "Cabinet Liberal"].map(value => <option key={value}>{labelFor(value)}</option>)}</select></Field><Field label="Téléphone"><Input value={form.phone} onChange={e => setForm({ ...form, phone: e.target.value })} className={inputClass} /></Field><Field label="Fonction"><Input value={form.jobTitle} onChange={e => setForm({ ...form, jobTitle: e.target.value })} className={inputClass} /></Field><Field label="Campagne"><select value={form.campaignId} onChange={e => setForm({ ...form, campaignId: e.target.value })} className={selectClass}><option value="none">Sans campagne</option>{campaigns.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field><Field label="Source"><select value={form.source} onChange={e => setForm({ ...form, source: e.target.value })} className={selectClass}>{["Site Web", "Import", "Evenement", "Manuel"].map(value => <option key={value}>{labelFor(value)}</option>)}</select></Field><Field label="Notes" className="sm:col-span-2"><Textarea value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} /></Field></div><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Annuler</Button><Button type="submit" disabled={mutation.isPending}>{mutation.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Ajouter le lead</Button></DialogFooter></form></DialogContent></Dialog>;
}

export function AssetDialog({ open, onOpenChange, campaigns }: { open: boolean; onOpenChange: (open: boolean) => void; campaigns: any[] }) {
  const utils = trpc.useUtils(); const mutation = trpc.marketing.assets.upload.useMutation();
  const [form, setForm] = useState({ campaignId: "none", title: "", assetType: "Plaquette", description: "" }); const [file, setFile] = useState<File | null>(null);
  const submit = async (event: FormEvent) => { event.preventDefault(); if (!file) return; try { const base64 = await new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); }); await mutation.mutateAsync({ campaignId: nullableNumber(form.campaignId), title: form.title, assetType: form.assetType as typeof assetTypes[number], description: form.description || null, fileName: file.name, mimeType: file.type || "application/octet-stream", base64 }); await utils.marketing.invalidate(); toast.success("Support ajouté à la bibliothèque"); onOpenChange(false); } catch (error) { toast.error(errorMessage(error)); } };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="sm:max-w-xl"><DialogHeader><DialogTitle>Ajouter un support</DialogTitle><DialogDescription>Importez un document de moins de 10 Mo dans l’espace sécurisé Medactio.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><Field label="Titre"><Input required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} className={inputClass} /></Field><div className="grid gap-4 sm:grid-cols-2"><Field label="Type"><select value={form.assetType} onChange={e => setForm({ ...form, assetType: e.target.value })} className={selectClass}>{assetTypes.map(value => <option key={value}>{labelFor(value)}</option>)}</select></Field><Field label="Campagne"><select value={form.campaignId} onChange={e => setForm({ ...form, campaignId: e.target.value })} className={selectClass}><option value="none">Support partagé</option>{campaigns.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></Field></div><Field label="Description"><Textarea value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></Field><label className="flex cursor-pointer items-center gap-3 rounded-xl border border-dashed border-slate-300 bg-slate-50 p-4 text-sm"><UploadCloud className="h-5 w-5 text-teal-600" /><span>{file?.name || "Choisir un fichier"}</span><input required type="file" className="sr-only" onChange={e => setFile(e.target.files?.[0] || null)} /></label><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Annuler</Button><Button type="submit" disabled={!file || mutation.isPending}>{mutation.isPending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Importer</Button></DialogFooter></form></DialogContent></Dialog>;
}
