import { Button } from "@/components/ui/button";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { trpc } from "@/lib/trpc";
import { FileUp, Loader2 } from "lucide-react";
import { FormEvent, useMemo, useState } from "react";
import { toast } from "sonner";
import { labelFor } from "./Common";

const fieldClass = "h-10 rounded-lg border-slate-200 bg-white focus:border-teal-600";
const selectClass = "h-10 w-full rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none focus:border-teal-600 focus:ring-2 focus:ring-teal-600/15";
const ticketCategories = ["Facturation", "Acces Licence", "Support Technique", "Onboarding", "Autre"] as const;
const ticketPriorities = ["Basse", "Moyenne", "Haute", "Urgente"] as const;
const ticketStatuses = ["Nouveau", "En cours", "En attente client", "Resolu"] as const;
const taskStatuses = ["A Faire", "En Cours", "Fait"] as const;
const invoiceStatuses = ["Brouillon", "Envoyee", "Payee", "En Retard"] as const;
const contractTypes = ["Convention", "Contrat", "DPA", "Avenant", "Autre"] as const;
const contractStatuses = ["Brouillon", "A Signer", "Actif", "Expire", "Resilie"] as const;
const eventTypes = ["Rendez-vous Interne", "Demo", "Rendez-vous Client", "Echeance", "Autre"] as const;

function Field({ label, children, className = "" }: { label: string; children: React.ReactNode; className?: string }) {
  return <div className={className}><Label className="mb-2 block text-xs font-semibold text-slate-600">{label}</Label>{children}</div>;
}
function errorMessage(error: unknown) { return error instanceof Error ? error.message : "Une erreur est survenue."; }
function dateValue(value?: Date | string | null) { return value ? new Date(value).toISOString().slice(0, 10) : ""; }
function dateTimeValue(value?: Date | string | null) { if (!value) return ""; const date = new Date(value); return new Date(date.getTime() - date.getTimezoneOffset() * 60_000).toISOString().slice(0, 16); }
async function fileToBase64(file: File) { return new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file); }); }

export function TicketDialog({ open, onOpenChange, initial }: { open: boolean; onOpenChange: (open: boolean) => void; initial?: any }) {
  const utils = trpc.useUtils();
  const organizations = trpc.crm.organizations.list.useQuery();
  const contacts = trpc.crm.contacts.list.useQuery();
  const users = trpc.support.users.useQuery();
  const [form, setForm] = useState({ organizationId: String(initial?.organizationId || "none"), contactId: String(initial?.contactId || "none"), title: initial?.title || "", description: initial?.description || "", category: initial?.category || "Support Technique", priority: initial?.priority || "Moyenne", status: initial?.status || "Nouveau", assignedTo: String(initial?.assignedTo || "none") });
  const availableContacts = useMemo(() => contacts.data?.filter(contact => form.organizationId === "none" || contact.organizationId === Number(form.organizationId)) || [], [contacts.data, form.organizationId]);
  const create = trpc.support.tickets.create.useMutation(); const update = trpc.support.tickets.update.useMutation(); const pending = create.isPending || update.isPending;
  const submit = async (event: FormEvent) => { event.preventDefault(); try {
    const payload = { organizationId: form.organizationId === "none" ? null : Number(form.organizationId), contactId: form.contactId === "none" ? null : Number(form.contactId), title: form.title, description: form.description || null, category: form.category as typeof ticketCategories[number], priority: form.priority as typeof ticketPriorities[number], status: form.status as typeof ticketStatuses[number], assignedTo: form.assignedTo === "none" ? null : Number(form.assignedTo) };
    if (initial?.id) await update.mutateAsync({ id: initial.id, ...payload }); else await create.mutateAsync(payload);
    await Promise.all([utils.support.tickets.invalidate(), utils.support.dashboard.invalidate(), utils.customerSuccess.invalidate()]); toast.success(initial ? "Ticket mis à jour" : "Ticket créé"); onOpenChange(false);
  } catch (error) { toast.error(errorMessage(error)); } };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{initial ? "Modifier le ticket" : "Nouveau ticket"}</DialogTitle><DialogDescription>Centralisez la demande, l’assignation et le délai cible de traitement.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2">
    <Field label="Objet" className="sm:col-span-2"><Input required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} className={fieldClass} /></Field>
    <Field label="Établissement"><select value={form.organizationId} onChange={e => setForm({ ...form, organizationId: e.target.value, contactId: "none" })} className={selectClass}><option value="none">Sans établissement</option>{organizations.data?.map(org => <option key={org.id} value={org.id}>{org.name}</option>)}</select></Field>
    <Field label="Contact"><select value={form.contactId} onChange={e => setForm({ ...form, contactId: e.target.value })} className={selectClass}><option value="none">Sans contact</option>{availableContacts.map(contact => <option key={contact.id} value={contact.id}>{contact.fullName}</option>)}</select></Field>
    <Field label="Catégorie"><select value={form.category} onChange={e => setForm({ ...form, category: e.target.value })} className={selectClass}>{ticketCategories.map(value => <option key={value} value={value}>{labelFor(value)}</option>)}</select></Field>
    <Field label="Priorité"><select value={form.priority} onChange={e => setForm({ ...form, priority: e.target.value })} className={selectClass}>{ticketPriorities.map(value => <option key={value} value={value}>{value}</option>)}</select></Field>
    <Field label="Statut"><select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })} className={selectClass}>{ticketStatuses.map(value => <option key={value} value={value}>{labelFor(value)}</option>)}</select></Field>
    <Field label="Assigné à"><select value={form.assignedTo} onChange={e => setForm({ ...form, assignedTo: e.target.value })} className={selectClass}><option value="none">Non assigné</option>{users.data?.filter(user => ["admin", "secretariat"].includes(user.role)).map(user => <option key={user.id} value={user.id}>{user.fullName}</option>)}</select></Field>
    <Field label="Description" className="sm:col-span-2"><Textarea value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} className="min-h-28" /></Field>
  </div><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Annuler</Button><Button type="submit" disabled={pending}>{pending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}{initial ? "Enregistrer" : "Créer le ticket"}</Button></DialogFooter></form></DialogContent></Dialog>;
}

export function TicketEventDialog({ open, onOpenChange, ticketId }: { open: boolean; onOpenChange: (open: boolean) => void; ticketId: number }) {
  const utils = trpc.useUtils(); const mutation = trpc.support.tickets.addEvent.useMutation(); const [form, setForm] = useState({ eventType: "Commentaire", content: "" });
  const submit = async (event: FormEvent) => { event.preventDefault(); try { await mutation.mutateAsync({ ticketId, eventType: form.eventType as "Commentaire" | "Changement Statut" | "Note Interne" | "Relance Client", content: form.content }); await Promise.all([utils.support.tickets.get.invalidate({ id: ticketId }), utils.support.tickets.list.invalidate(), utils.support.dashboard.invalidate()]); toast.success("Événement ajouté"); onOpenChange(false); } catch (error) { toast.error(errorMessage(error)); } };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Ajouter au journal</DialogTitle><DialogDescription>Consignez une réponse, une note interne ou une relance client.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-4"><Field label="Type"><select value={form.eventType} onChange={e => setForm({ ...form, eventType: e.target.value })} className={selectClass}>{["Commentaire", "Note Interne", "Relance Client"].map(value => <option key={value} value={value}>{value}</option>)}</select></Field><Field label="Contenu"><Textarea required value={form.content} onChange={e => setForm({ ...form, content: e.target.value })} className="min-h-32" /></Field><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Annuler</Button><Button type="submit" disabled={mutation.isPending}>Ajouter au journal</Button></DialogFooter></form></DialogContent></Dialog>;
}

export function TaskDialog({ open, onOpenChange, initial }: { open: boolean; onOpenChange: (open: boolean) => void; initial?: any }) {
  const utils = trpc.useUtils(); const organizations = trpc.crm.organizations.list.useQuery(); const users = trpc.support.users.useQuery();
  const [form, setForm] = useState({ title: initial?.title || "", description: initial?.description || "", organizationId: String(initial?.organizationId || "none"), assignedTo: String(initial?.assignedTo || "none"), dueDate: dateValue(initial?.dueDate), priority: initial?.priority || "Moyenne", status: initial?.status || "A Faire" });
  const create = trpc.support.tasks.create.useMutation(); const update = trpc.support.tasks.update.useMutation(); const pending = create.isPending || update.isPending;
  const submit = async (event: FormEvent) => { event.preventDefault(); try { const payload = { title: form.title, description: form.description || null, organizationId: form.organizationId === "none" ? null : Number(form.organizationId), assignedTo: form.assignedTo === "none" ? null : Number(form.assignedTo), dueDate: form.dueDate || null, priority: form.priority as "Basse" | "Moyenne" | "Haute", status: form.status as typeof taskStatuses[number] }; if (initial?.id) await update.mutateAsync({ id: initial.id, ...payload }); else await create.mutateAsync(payload); await Promise.all([utils.support.tasks.invalidate(), utils.support.dashboard.invalidate()]); toast.success(initial ? "Tâche mise à jour" : "Tâche créée"); onOpenChange(false); } catch (error) { toast.error(errorMessage(error)); } };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>{initial ? "Modifier la tâche" : "Nouvelle tâche"}</DialogTitle><DialogDescription>Planifiez une action administrative et son échéance.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Intitulé" className="sm:col-span-2"><Input required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></Field><Field label="Établissement"><select value={form.organizationId} onChange={e => setForm({ ...form, organizationId: e.target.value })} className={selectClass}><option value="none">Tâche interne</option>{organizations.data?.map(org => <option key={org.id} value={org.id}>{org.name}</option>)}</select></Field><Field label="Assigné à"><select value={form.assignedTo} onChange={e => setForm({ ...form, assignedTo: e.target.value })} className={selectClass}><option value="none">Non assigné</option>{users.data?.map(user => <option key={user.id} value={user.id}>{user.fullName}</option>)}</select></Field><Field label="Échéance"><Input type="date" value={form.dueDate} onChange={e => setForm({ ...form, dueDate: e.target.value })} /></Field><Field label="Priorité"><select value={form.priority} onChange={e => setForm({ ...form, priority: e.target.value })} className={selectClass}>{["Basse", "Moyenne", "Haute"].map(value => <option key={value}>{value}</option>)}</select></Field><Field label="Statut"><select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })} className={selectClass}>{taskStatuses.map(value => <option key={value} value={value}>{labelFor(value)}</option>)}</select></Field><Field label="Description" className="sm:col-span-2"><Textarea value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} className="min-h-24" /></Field></div><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Annuler</Button><Button type="submit" disabled={pending}>{initial ? "Enregistrer" : "Créer la tâche"}</Button></DialogFooter></form></DialogContent></Dialog>;
}

export function InvoiceDialog({ open, onOpenChange, initial }: { open: boolean; onOpenChange: (open: boolean) => void; initial?: any }) {
  const utils = trpc.useUtils(); const organizations = trpc.crm.organizations.list.useQuery();
  const [form, setForm] = useState({ organizationId: String(initial?.organizationId || ""), invoiceNumber: initial?.invoiceNumber || `FAC-${new Date().getFullYear()}-`, amount: String(initial?.amount || ""), status: initial?.status || "Brouillon", issuedAt: dateValue(initial?.issuedAt), dueDate: dateValue(initial?.dueDate), paidAt: dateValue(initial?.paidAt), nextReminderDate: dateValue(initial?.nextReminderDate), notes: initial?.notes || "" });
  const create = trpc.support.invoices.create.useMutation(); const update = trpc.support.invoices.update.useMutation(); const pending = create.isPending || update.isPending;
  const submit = async (event: FormEvent) => { event.preventDefault(); try { const payload = { organizationId: Number(form.organizationId), subscriptionId: null, invoiceNumber: form.invoiceNumber, amount: Number(form.amount), status: form.status as typeof invoiceStatuses[number], issuedAt: form.issuedAt || null, dueDate: form.dueDate || null, paidAt: form.paidAt || null, nextReminderDate: form.nextReminderDate || null, notes: form.notes || null }; if (initial?.id) await update.mutateAsync({ id: initial.id, ...payload }); else await create.mutateAsync(payload); await Promise.all([utils.support.invoices.invalidate(), utils.support.dashboard.invalidate()]); toast.success(initial ? "Facture mise à jour" : "Facture créée"); onOpenChange(false); } catch (error) { toast.error(errorMessage(error)); } };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>{initial ? "Modifier la facture" : "Nouvelle facture"}</DialogTitle><DialogDescription>Suivez l’émission, l’échéance, le paiement et les relances.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Établissement" className="sm:col-span-2"><select required value={form.organizationId} onChange={e => setForm({ ...form, organizationId: e.target.value })} className={selectClass}><option value="" disabled>Sélectionner</option>{organizations.data?.map(org => <option key={org.id} value={org.id}>{org.name}</option>)}</select></Field><Field label="Numéro"><Input required value={form.invoiceNumber} onChange={e => setForm({ ...form, invoiceNumber: e.target.value })} /></Field><Field label="Montant"><Input required min="0.01" step="0.01" type="number" value={form.amount} onChange={e => setForm({ ...form, amount: e.target.value })} /></Field><Field label="Statut"><select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })} className={selectClass}>{invoiceStatuses.map(value => <option key={value} value={value}>{labelFor(value)}</option>)}</select></Field><Field label="Date d’émission"><Input type="date" value={form.issuedAt} onChange={e => setForm({ ...form, issuedAt: e.target.value })} /></Field><Field label="Échéance"><Input type="date" value={form.dueDate} onChange={e => setForm({ ...form, dueDate: e.target.value })} /></Field><Field label="Paiement reçu le"><Input type="date" value={form.paidAt} onChange={e => setForm({ ...form, paidAt: e.target.value })} /></Field><Field label="Prochaine relance"><Input type="date" value={form.nextReminderDate} onChange={e => setForm({ ...form, nextReminderDate: e.target.value })} /></Field><Field label="Notes" className="sm:col-span-2"><Textarea value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} /></Field></div><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Annuler</Button><Button type="submit" disabled={pending}>{initial ? "Enregistrer" : "Créer la facture"}</Button></DialogFooter></form></DialogContent></Dialog>;
}

export function ContractDialog({ open, onOpenChange, initial }: { open: boolean; onOpenChange: (open: boolean) => void; initial?: any }) {
  const utils = trpc.useUtils(); const organizations = trpc.crm.organizations.list.useQuery(); const [file, setFile] = useState<File | null>(null);
  const [form, setForm] = useState({ organizationId: String(initial?.organizationId || ""), title: initial?.title || "", type: initial?.type || "Contrat", status: initial?.status || "Brouillon", startDate: dateValue(initial?.startDate), endDate: dateValue(initial?.endDate), signedAt: dateValue(initial?.signedAt), notes: initial?.notes || "" });
  const create = trpc.support.contracts.create.useMutation(); const update = trpc.support.contracts.update.useMutation(); const upload = trpc.support.contracts.upload.useMutation(); const pending = create.isPending || update.isPending || upload.isPending;
  const submit = async (event: FormEvent) => { event.preventDefault(); try { const payload = { organizationId: Number(form.organizationId), title: form.title, type: form.type as typeof contractTypes[number], status: form.status as typeof contractStatuses[number], startDate: form.startDate || null, endDate: form.endDate || null, signedAt: form.signedAt || null, notes: form.notes || null }; const result = initial?.id ? (await update.mutateAsync({ id: initial.id, ...payload }), { id: initial.id }) : await create.mutateAsync(payload); if (file) await upload.mutateAsync({ id: result.id, fileName: file.name, mimeType: file.type || "application/octet-stream", base64: await fileToBase64(file) }); await Promise.all([utils.support.contracts.invalidate(), utils.support.dashboard.invalidate()]); toast.success(file ? "Contrat et document enregistrés" : initial ? "Contrat mis à jour" : "Contrat créé"); onOpenChange(false); } catch (error) { toast.error(errorMessage(error)); } };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-xl"><DialogHeader><DialogTitle>{initial ? "Modifier le contrat" : "Nouveau contrat"}</DialogTitle><DialogDescription>Centralisez les dates clés et le document signé de l’établissement.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Établissement" className="sm:col-span-2"><select required value={form.organizationId} onChange={e => setForm({ ...form, organizationId: e.target.value })} className={selectClass}><option value="" disabled>Sélectionner</option>{organizations.data?.map(org => <option key={org.id} value={org.id}>{org.name}</option>)}</select></Field><Field label="Intitulé" className="sm:col-span-2"><Input required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></Field><Field label="Type"><select value={form.type} onChange={e => setForm({ ...form, type: e.target.value })} className={selectClass}>{contractTypes.map(value => <option key={value}>{value}</option>)}</select></Field><Field label="Statut"><select value={form.status} onChange={e => setForm({ ...form, status: e.target.value })} className={selectClass}>{contractStatuses.map(value => <option key={value} value={value}>{labelFor(value)}</option>)}</select></Field><Field label="Début"><Input type="date" value={form.startDate} onChange={e => setForm({ ...form, startDate: e.target.value })} /></Field><Field label="Fin / renouvellement"><Input type="date" value={form.endDate} onChange={e => setForm({ ...form, endDate: e.target.value })} /></Field><Field label="Signature"><Input type="date" value={form.signedAt} onChange={e => setForm({ ...form, signedAt: e.target.value })} /></Field><Field label="Document (10 Mo max.)"><label className="flex h-10 cursor-pointer items-center gap-2 rounded-lg border border-dashed px-3 text-sm text-slate-600"><FileUp className="h-4 w-4" /><span className="truncate">{file?.name || initial?.documentName || "Choisir un fichier"}</span><input className="hidden" type="file" accept=".pdf,.doc,.docx,image/*" onChange={e => setFile(e.target.files?.[0] || null)} /></label></Field><Field label="Notes" className="sm:col-span-2"><Textarea value={form.notes} onChange={e => setForm({ ...form, notes: e.target.value })} /></Field></div><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Annuler</Button><Button type="submit" disabled={pending}>{pending && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}{initial ? "Enregistrer" : "Créer le contrat"}</Button></DialogFooter></form></DialogContent></Dialog>;
}

export function CalendarEventDialog({ open, onOpenChange, initial }: { open: boolean; onOpenChange: (open: boolean) => void; initial?: any }) {
  const utils = trpc.useUtils(); const organizations = trpc.crm.organizations.list.useQuery(); const contacts = trpc.crm.contacts.list.useQuery(); const users = trpc.support.users.useQuery();
  const [form, setForm] = useState({ title: initial?.title || "", description: initial?.description || "", eventType: initial?.eventType || "Rendez-vous Interne", organizationId: String(initial?.organizationId || "none"), contactId: String(initial?.contactId || "none"), organizerId: String(initial?.organizerId || "none"), startAt: dateTimeValue(initial?.startAt), endAt: dateTimeValue(initial?.endAt), allDay: initial?.allDay || false, location: initial?.location || "" });
  const create = trpc.support.events.create.useMutation(); const update = trpc.support.events.update.useMutation(); const pending = create.isPending || update.isPending;
  const submit = async (event: FormEvent) => { event.preventDefault(); try { const payload = { title: form.title, description: form.description || null, eventType: form.eventType as typeof eventTypes[number], organizationId: form.organizationId === "none" ? null : Number(form.organizationId), contactId: form.contactId === "none" ? null : Number(form.contactId), organizerId: form.organizerId === "none" ? null : Number(form.organizerId), startAt: new Date(form.startAt), endAt: form.endAt ? new Date(form.endAt) : null, allDay: form.allDay, location: form.location || null }; if (initial?.id) await update.mutateAsync({ id: initial.id, ...payload }); else await create.mutateAsync(payload); await Promise.all([utils.support.events.invalidate(), utils.support.dashboard.invalidate()]); toast.success(initial ? "Événement mis à jour" : "Événement ajouté"); onOpenChange(false); } catch (error) { toast.error(errorMessage(error)); } };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="max-h-[90vh] overflow-y-auto sm:max-w-2xl"><DialogHeader><DialogTitle>{initial ? "Modifier l’événement" : "Nouvel événement"}</DialogTitle><DialogDescription>Planifiez un rendez-vous interne, client, une démo ou une échéance.</DialogDescription></DialogHeader><form onSubmit={submit} className="space-y-5"><div className="grid gap-4 sm:grid-cols-2"><Field label="Intitulé" className="sm:col-span-2"><Input required value={form.title} onChange={e => setForm({ ...form, title: e.target.value })} /></Field><Field label="Type"><select value={form.eventType} onChange={e => setForm({ ...form, eventType: e.target.value })} className={selectClass}>{eventTypes.map(value => <option key={value} value={value}>{labelFor(value)}</option>)}</select></Field><Field label="Organisateur"><select value={form.organizerId} onChange={e => setForm({ ...form, organizerId: e.target.value })} className={selectClass}><option value="none">Non défini</option>{users.data?.map(user => <option key={user.id} value={user.id}>{user.fullName}</option>)}</select></Field><Field label="Établissement"><select value={form.organizationId} onChange={e => setForm({ ...form, organizationId: e.target.value, contactId: "none" })} className={selectClass}><option value="none">Aucun</option>{organizations.data?.map(org => <option key={org.id} value={org.id}>{org.name}</option>)}</select></Field><Field label="Contact"><select value={form.contactId} onChange={e => setForm({ ...form, contactId: e.target.value })} className={selectClass}><option value="none">Aucun</option>{contacts.data?.filter(contact => form.organizationId === "none" || contact.organizationId === Number(form.organizationId)).map(contact => <option key={contact.id} value={contact.id}>{contact.fullName}</option>)}</select></Field><Field label="Début"><Input required type="datetime-local" value={form.startAt} onChange={e => setForm({ ...form, startAt: e.target.value })} /></Field><Field label="Fin"><Input type="datetime-local" value={form.endAt} onChange={e => setForm({ ...form, endAt: e.target.value })} /></Field><Field label="Lieu"><Input value={form.location} onChange={e => setForm({ ...form, location: e.target.value })} /></Field><Field label="Journée entière"><label className="flex h-10 items-center gap-2 rounded-lg border px-3 text-sm"><input type="checkbox" checked={form.allDay} onChange={e => setForm({ ...form, allDay: e.target.checked })} /> Oui</label></Field><Field label="Description" className="sm:col-span-2"><Textarea value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} /></Field></div><DialogFooter><Button type="button" variant="outline" onClick={() => onOpenChange(false)}>Annuler</Button><Button type="submit" disabled={pending}>{initial ? "Enregistrer" : "Ajouter à l’agenda"}</Button></DialogFooter></form></DialogContent></Dialog>;
}
