import { canWriteSupport, EmptyState, formatDate, labelFor, PageHeader, StatusBadge } from "@/components/crm/Common";
import { DeleteDialog } from "@/components/crm/Forms";
import { TaskDialog } from "@/components/crm/SupportForms";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { trpc } from "@/lib/trpc";
import { Check, ClipboardCheck, Loader2, Pencil, Search, Trash2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function AdminTasks() {
  const utils = trpc.useUtils(); const profile = trpc.support.profile.useQuery(); const [search, setSearch] = useState(""); const [status, setStatus] = useState("Tous"); const [dialog, setDialog] = useState<{ open: boolean; item?: any }>({ open: false }); const [deleting, setDeleting] = useState<any>(null);
  const query = trpc.support.tasks.list.useQuery({ search, status }); const update = trpc.support.tasks.update.useMutation(); const remove = trpc.support.tasks.delete.useMutation(); const canWrite = canWriteSupport(profile.data?.role);
  const complete = async (id: number) => { try { await update.mutateAsync({ id, status: "Fait" }); await Promise.all([query.refetch(), utils.support.dashboard.invalidate()]); toast.success("Tâche terminée"); } catch (error) { toast.error(error instanceof Error ? error.message : "Mise à jour impossible"); } };
  const confirmDelete = async () => { if (!deleting) return; await remove.mutateAsync({ id: deleting.id }); await Promise.all([query.refetch(), utils.support.dashboard.invalidate()]); setDeleting(null); toast.success("Tâche supprimée"); };
  const done = query.data?.filter(task => task.status === "Fait").length || 0; const total = query.data?.length || 0;
  return <div><PageHeader eyebrow="Secrétariat & Support" title="Tâches administratives" description="Assignez les actions quotidiennes, pilotez les échéances et visualisez les retards." actionLabel={canWrite ? "Nouvelle tâche" : undefined} onAction={() => setDialog({ open: true })} />
    <Card className="mb-5 border-0 shadow-sm"><CardContent className="grid gap-4 p-4 md:grid-cols-[1fr_180px_260px]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="Rechercher une tâche…" className="pl-9" /></div><select value={status} onChange={e => setStatus(e.target.value)} className="h-10 rounded-lg border bg-white px-3 text-sm">{["Tous", "A Faire", "En Cours", "Fait"].map(value => <option key={value} value={value}>{labelFor(value)}</option>)}</select><div className="rounded-xl bg-slate-50 px-4 py-2"><div className="mb-1 flex justify-between text-xs"><span className="font-medium">Avancement</span><span>{done}/{total}</span></div><Progress value={total ? done / total * 100 : 0} className="h-1.5" /></div></CardContent></Card>
    {query.isLoading ? <div className="flex min-h-64 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin" /></div> : query.data?.length ? <div className="grid gap-3 lg:grid-cols-2">{query.data.map(task => <Card key={task.id} className={`border-0 shadow-sm ${task.status === "Fait" ? "opacity-70" : ""}`}><CardContent className="p-5"><div className="flex items-start gap-4"><button disabled={!canWrite || task.status === "Fait"} onClick={() => complete(task.id)} className={`mt-0.5 flex h-6 w-6 shrink-0 items-center justify-center rounded-full border-2 ${task.status === "Fait" ? "border-emerald-500 bg-emerald-500 text-white" : "border-slate-300 hover:border-teal-500"}`}>{task.status === "Fait" && <Check className="h-3.5 w-3.5" />}</button><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className={`font-semibold ${task.status === "Fait" ? "line-through" : ""}`}>{task.title}</p><StatusBadge value={task.priority} /><StatusBadge value={task.status} /></div><p className="mt-2 text-sm leading-6 text-muted-foreground">{task.description || "Aucune description."}</p><div className="mt-4 flex flex-wrap items-center gap-x-5 gap-y-1 text-xs text-muted-foreground"><span>{task.organizationName || "Tâche interne"}</span><span>{task.assignedToName || "Non assignée"}</span><span className={task.status !== "Fait" && Number(task.daysUntilDue) < 0 ? "font-semibold text-rose-600" : ""}>{task.dueDate ? `Échéance ${formatDate(task.dueDate)}` : "Sans échéance"}</span></div></div>{canWrite && <div className="flex shrink-0"><Button size="icon" variant="ghost" onClick={() => setDialog({ open: true, item: task })}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" className="text-rose-600" onClick={() => setDeleting(task)}><Trash2 className="h-4 w-4" /></Button></div>}</div></CardContent></Card>)}</div> : <EmptyState icon={ClipboardCheck} title="Aucune tâche" description="Ajoutez les actions administratives à planifier." actionLabel={canWrite ? "Nouvelle tâche" : undefined} onAction={() => setDialog({ open: true })} />}
    {dialog.open && <TaskDialog key={dialog.item?.id || "new"} open={dialog.open} onOpenChange={open => setDialog({ open })} initial={dialog.item} />}
    <DeleteDialog open={!!deleting} onOpenChange={open => !open && setDeleting(null)} title="Supprimer cette tâche ?" description="Cette action ne pourra pas être annulée." onConfirm={confirmDelete} pending={remove.isPending} />
  </div>;
}
