import { canWriteSupport, EmptyState, formatDate, labelFor, PageHeader, StatusBadge } from "@/components/crm/Common";
import { DeleteDialog } from "@/components/crm/Forms";
import { ContractDialog } from "@/components/crm/SupportForms";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { Download, FileCheck2, Loader2, Pencil, Search, Trash2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function Contracts() {
  const utils = trpc.useUtils(); const profile = trpc.support.profile.useQuery(); const [search, setSearch] = useState(""); const [status, setStatus] = useState("Tous"); const [type, setType] = useState("Tous"); const [dialog, setDialog] = useState<{ open: boolean; item?: any }>({ open: false }); const [deleting, setDeleting] = useState<any>(null);
  const query = trpc.support.contracts.list.useQuery({ search, status, type }); const remove = trpc.support.contracts.delete.useMutation(); const canWrite = canWriteSupport(profile.data?.role);
  const confirmDelete = async () => { if (!deleting) return; await remove.mutateAsync({ id: deleting.id }); await Promise.all([query.refetch(), utils.support.dashboard.invalidate()]); setDeleting(null); toast.success("Contrat supprimé"); };
  return <div><PageHeader eyebrow="Secrétariat & Support" title="Conventions & contrats" description="Retrouvez les accords signés, documents associés et échéances de renouvellement." actionLabel={canWrite ? "Nouveau contrat" : undefined} onAction={() => setDialog({ open: true })} />
    <Card className="mb-5 border-0 shadow-sm"><CardContent className="grid gap-3 p-4 md:grid-cols-[1fr_180px_180px]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="Contrat ou établissement…" className="pl-9" /></div><select value={type} onChange={e => setType(e.target.value)} className="h-10 rounded-lg border bg-white px-3 text-sm">{["Tous", "Convention", "Contrat", "DPA", "Avenant", "Autre"].map(value => <option key={value}>{value}</option>)}</select><select value={status} onChange={e => setStatus(e.target.value)} className="h-10 rounded-lg border bg-white px-3 text-sm">{["Tous", "Brouillon", "A Signer", "Actif", "Expire", "Resilie"].map(value => <option key={value} value={value}>{labelFor(value)}</option>)}</select></CardContent></Card>
    {query.isLoading ? <div className="flex min-h-64 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin" /></div> : query.data?.length ? <div className="grid gap-4 lg:grid-cols-2">{query.data.map(contract => <Card key={contract.id} className="border-0 shadow-sm"><CardContent className="p-5"><div className="flex items-start gap-4"><div className="rounded-xl bg-teal-50 p-3 text-teal-700"><FileCheck2 className="h-5 w-5" /></div><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{contract.title}</p><StatusBadge value={contract.status} /></div><p className="mt-1 text-sm text-muted-foreground">{contract.organizationName} · {contract.type}</p><div className="mt-4 grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-3 text-xs"><div><p className="text-muted-foreground">Signature</p><p className="mt-1 font-medium">{formatDate(contract.signedAt)}</p></div><div><p className="text-muted-foreground">Échéance</p><p className={`mt-1 font-medium ${contract.status === "Actif" && contract.daysUntilEnd !== null && contract.daysUntilEnd <= 30 ? "text-rose-600" : ""}`}>{formatDate(contract.endDate)}{contract.daysUntilEnd !== null && contract.daysUntilEnd >= 0 ? ` · J-${contract.daysUntilEnd}` : ""}</p></div></div>{contract.notes && <p className="mt-3 line-clamp-2 text-xs leading-5 text-muted-foreground">{contract.notes}</p>}</div></div><div className="mt-4 flex flex-wrap items-center justify-end gap-2">{contract.documentUrl ? <Button variant="outline" size="sm" asChild className="bg-white"><a href={contract.documentUrl} target="_blank" rel="noreferrer"><Download className="mr-2 h-4 w-4" />{contract.documentName || "Document"}</a></Button> : <span className="mr-auto text-xs text-muted-foreground">Aucun document joint</span>}{canWrite && <><Button size="icon" variant="ghost" onClick={() => setDialog({ open: true, item: contract })}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" className="text-rose-600" onClick={() => setDeleting(contract)}><Trash2 className="h-4 w-4" /></Button></>}</div></CardContent></Card>)}</div> : <EmptyState icon={FileCheck2} title="Aucun contrat" description="Ajoutez les conventions et documents signés des établissements." actionLabel={canWrite ? "Nouveau contrat" : undefined} onAction={() => setDialog({ open: true })} />}
    {dialog.open && <ContractDialog key={dialog.item?.id || "new"} open={dialog.open} onOpenChange={open => setDialog({ open })} initial={dialog.item} />}
    <DeleteDialog open={!!deleting} onOpenChange={open => !open && setDeleting(null)} title="Supprimer ce contrat ?" description="Le registre sera mis à jour ; le fichier non référencé deviendra inaccessible." onConfirm={confirmDelete} pending={remove.isPending} />
  </div>;
}
