import { canWriteSubscriptions, EmptyState, formatDate, labelFor, PageHeader, StatusBadge } from "@/components/crm/Common";
import { SubscriptionDialog } from "@/components/crm/CustomerSuccessForms";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { Activity, CalendarDays, ChevronRight, HeartPulse, Search, ShieldCheck, UsersRound } from "lucide-react";
import { useState } from "react";
import { useLocation } from "wouter";

export default function Customers() {
  const [, setLocation] = useLocation(); const [search, setSearch] = useState(""); const [health, setHealth] = useState("Tous"); const [onboarding, setOnboarding] = useState("Tous"); const [renewal, setRenewal] = useState("Tous"); const [subscriptionOpen, setSubscriptionOpen] = useState(false);
  const profile = trpc.crm.profile.useQuery(); const query = trpc.customerSuccess.list.useQuery({ search, health, onboarding, renewal }); const canWrite = canWriteSubscriptions(profile.data?.role);
  return <div className="reveal mx-auto max-w-[1500px]"><PageHeader eyebrow="Portefeuille client" title="Comptes clients" description="Suivez l’onboarding, l’activation des licences, l’usage et les échéances contractuelles." actionLabel={canWrite ? "Activer un client" : undefined} onAction={() => setSubscriptionOpen(true)} />
    <Card className="soft-card overflow-hidden"><div className="grid gap-3 border-b border-slate-100 p-4 md:grid-cols-[minmax(240px,1fr)_160px_160px_150px_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><Input value={search} onChange={event => setSearch(event.target.value)} placeholder="Rechercher un client, une ville ou un plan…" className="h-10 border-slate-200 pl-9" /></div><Filter value={health} onChange={setHealth} options={["Tous", "Bon", "A Surveiller", "A Risque"]} /><Filter value={onboarding} onChange={setOnboarding} options={["Tous", "Non Demarre", "En Cours", "Termine"]} /><Filter value={renewal} onChange={setRenewal} options={["Tous", "30", "60", "90"]} render={value => value === "Tous" ? "Toutes échéances" : `Renouvellement ≤ ${value} j`} /><span className="self-center text-xs font-medium text-muted-foreground">{query.data?.length || 0} compte{query.data?.length === 1 ? "" : "s"}</span></div>
      {query.isLoading ? <div className="space-y-2 p-4">{[1,2,3,4].map(i => <Skeleton key={i} className="h-24" />)}</div> : query.data?.length ? <div className="divide-y divide-slate-100">{query.data.map(customer => <button key={customer.organizationId} onClick={() => setLocation(`/clients/${customer.organizationId}`)} className="grid w-full gap-4 p-4 text-left transition-colors hover:bg-slate-50/70 md:grid-cols-[minmax(260px,1.4fr)_150px_170px_150px_110px_16px] md:items-center"><div className="flex min-w-0 items-center gap-3"><div className={`flex h-11 w-11 shrink-0 items-center justify-center rounded-xl text-sm font-bold ${customer.healthLabel === "Bon" ? "bg-emerald-50 text-emerald-700" : customer.healthLabel === "A Surveiller" ? "bg-amber-50 text-amber-700" : "bg-rose-50 text-rose-700"}`}>{customer.healthScore}</div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="truncate text-sm font-semibold text-slate-950">{customer.organizationName}</p><StatusBadge value={customer.healthLabel} /></div><p className="mt-1 truncate text-xs text-muted-foreground">{customer.city || "Ville non renseignée"} · {customer.planName || "Sans abonnement"}</p></div></div><div><p className="text-xs text-muted-foreground">Onboarding</p><div className="mt-1.5 flex items-center gap-2"><Progress value={customer.onboardingProgress} className="h-1.5 w-20" /><span className="text-xs font-semibold">{customer.onboardingProgress} %</span></div></div><div><p className="text-xs text-muted-foreground">Licences</p><p className="mt-1 flex items-center gap-1.5 text-sm font-semibold"><ShieldCheck className="h-4 w-4 text-teal-700" />{customer.activeSeats} / {customer.seatsPurchased} actives</p></div><div><p className="text-xs text-muted-foreground">Usage 30 jours</p><p className="mt-1 flex items-center gap-1.5 text-sm font-semibold"><Activity className="h-4 w-4 text-violet-700" />{customer.documentsLast30} écrits</p></div><div><p className="text-xs text-muted-foreground">Renouvellement</p><p className={`mt-1 flex items-center gap-1 text-sm font-semibold ${customer.daysUntilRenewal !== null && customer.daysUntilRenewal <= 30 ? "text-rose-700" : "text-slate-800"}`}><CalendarDays className="h-4 w-4" />{customer.daysUntilRenewal !== null && customer.daysUntilRenewal >= 0 ? `J-${customer.daysUntilRenewal}` : formatDate(customer.renewalDate)}</p></div><ChevronRight className="hidden h-4 w-4 text-slate-300 md:block" /></button>)}</div> : <div className="p-4"><EmptyState icon={UsersRound} title="Aucun compte client" description="Aucun établissement ne correspond aux filtres sélectionnés." actionLabel={canWrite ? "Activer un client" : undefined} onAction={() => setSubscriptionOpen(true)} /></div>}
    </Card>{subscriptionOpen ? <SubscriptionDialog open={subscriptionOpen} onOpenChange={setSubscriptionOpen} /> : null}
  </div>;
}

function Filter({ value, onChange, options, render = labelFor }: { value: string; onChange: (value: string) => void; options: string[]; render?: (value: string) => string }) { return <select value={value} onChange={event => onChange(event.target.value)} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm outline-none focus:border-teal-600">{options.map(option => <option key={option} value={option}>{render(option)}</option>)}</select>; }
