import { canWriteCustomerSuccess, EmptyState, formatCurrency, formatDate, labelFor, PageHeader, StatCard, StatusBadge } from "@/components/crm/Common";
import { SubscriptionDialog } from "@/components/crm/CustomerSuccessForms";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { Activity, AlertTriangle, ArrowRight, BellRing, CalendarClock, CheckCircle2, CircleDollarSign, HeartPulse, Loader2, RefreshCw, ShieldCheck, UsersRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

export default function CustomerSuccessDashboard() {
  const [, setLocation] = useLocation(); const utils = trpc.useUtils(); const [subscriptionOpen, setSubscriptionOpen] = useState(false);
  const profile = trpc.crm.profile.useQuery(); const query = trpc.customerSuccess.dashboard.useQuery(); const automation = trpc.customerSuccess.automation.status.useQuery();
  const refresh = trpc.customerSuccess.alerts.refresh.useMutation(); const enable = trpc.customerSuccess.automation.enable.useMutation(); const disable = trpc.customerSuccess.automation.disable.useMutation(); const updateAlert = trpc.customerSuccess.alerts.updateStatus.useMutation();
  const canWrite = canWriteCustomerSuccess(profile.data?.role);
  const refreshAlerts = async () => { try { const result = await refresh.mutateAsync(); await utils.customerSuccess.invalidate(); toast.success(`${result.alerts} alertes analysées`); } catch (error) { toast.error(error instanceof Error ? error.message : "Recalcul impossible"); } };
  const toggleAutomation = async () => { try { if (automation.data?.enabled) await disable.mutateAsync(); else await enable.mutateAsync(); await automation.refetch(); toast.success(automation.data?.enabled ? "Automatisation désactivée" : "Automatisation quotidienne activée"); } catch (error) { toast.error(error instanceof Error ? error.message : "Activez d’abord le site publié pour planifier le traitement quotidien."); } };
  if (query.isLoading) return <DashboardSkeleton />;
  if (!query.data) return <EmptyState icon={HeartPulse} title="Données indisponibles" description="Le tableau de bord Succès Client n’a pas pu être chargé." />;
  const data = query.data;
  return <div className="reveal mx-auto max-w-[1500px]">
    <PageHeader eyebrow="Succès Client" title="Clients & licences" description="Pilotez l’activation, l’adoption et les renouvellements des établissements clients." actionLabel={canWrite ? "Activer un client" : undefined} onAction={() => setSubscriptionOpen(true)} />
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
      <StatCard label="Clients actifs" value={String(data.activeCustomers)} detail={`${data.incompleteOnboarding} onboarding${data.incompleteOnboarding > 1 ? "s" : ""} à finaliser`} icon={UsersRound} />
      <StatCard label="Licences actives" value={`${data.activeSeats} / ${data.seatsPurchased}`} detail={`${data.seatActivationRate} % des sièges activés`} icon={ShieldCheck} accent="teal" />
      <StatCard label="Écrits sur 30 jours" value={data.documentsLast30.toLocaleString("fr-FR")} detail="Tous établissements confondus" icon={Activity} accent="violet" />
      <StatCard label="Renouvellements à 90 j" value={String(data.renewingSoon)} detail={`${formatCurrency(data.mrr)} de MRR estimé`} icon={CalendarClock} accent="amber" />
    </div>

    <div className="mt-5 grid gap-5 xl:grid-cols-[1.25fr_.75fr]">
      <Card className="soft-card"><CardHeader className="flex flex-row items-start justify-between gap-4"><div><CardTitle className="flex items-center gap-2 text-base"><BellRing className="h-4 w-4 text-amber-600" /> Centre d’alertes</CardTitle><p className="mt-1 text-xs text-muted-foreground">Renouvellements, sous-utilisation et comptes à risque</p></div>{canWrite ? <Button variant="outline" size="sm" className="bg-white" disabled={refresh.isPending} onClick={refreshAlerts}>{refresh.isPending ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <RefreshCw className="mr-2 h-4 w-4" />}Recalculer</Button> : null}</CardHeader><CardContent>{data.alerts.length ? <div className="space-y-2">{data.alerts.slice(0, 8).map(alert => <div key={alert.id} className="group flex items-start gap-3 rounded-xl border border-slate-100 p-3 hover:bg-slate-50/70"><div className={`mt-0.5 rounded-lg p-2 ${alert.severity === "Critique" ? "bg-rose-50 text-rose-700" : alert.severity === "Attention" ? "bg-amber-50 text-amber-700" : "bg-sky-50 text-sky-700"}`}><AlertTriangle className="h-4 w-4" /></div><button onClick={() => setLocation(`/clients/${alert.organizationId}`)} className="min-w-0 flex-1 text-left"><div className="flex flex-wrap items-center gap-2"><p className="text-sm font-semibold text-slate-900">{alert.title}</p><StatusBadge value={alert.severity} /></div><p className="mt-1 text-xs leading-5 text-muted-foreground">{alert.message}</p>{alert.dueDate ? <p className="mt-1 text-xs font-medium text-amber-700">Échéance : {formatDate(alert.dueDate)}</p> : null}</button>{canWrite ? <Button variant="ghost" size="sm" className="text-xs text-emerald-700 opacity-100 sm:opacity-0 sm:group-hover:opacity-100" onClick={async () => { await updateAlert.mutateAsync({ id: alert.id, status: "Resolue" }); await utils.customerSuccess.dashboard.invalidate(); toast.success("Alerte résolue"); }}><CheckCircle2 className="mr-1 h-4 w-4" />Résoudre</Button> : null}</div>)}</div> : <EmptyState icon={CheckCircle2} title="Aucune alerte ouverte" description="Les comptes actifs ne nécessitent aucune action immédiate." />}</CardContent></Card>

      <div className="space-y-5"><Card className="soft-card"><CardHeader><CardTitle className="text-base">Santé du portefeuille</CardTitle></CardHeader><CardContent className="space-y-5"><HealthLine label="Bonne santé" count={data.activeCustomers - data.atRiskCustomers - data.monitoredCustomers} total={data.activeCustomers} color="bg-emerald-500" /><HealthLine label="À surveiller" count={data.monitoredCustomers} total={data.activeCustomers} color="bg-amber-500" /><HealthLine label="À risque" count={data.atRiskCustomers} total={data.activeCustomers} color="bg-rose-500" /><div className="rounded-xl bg-slate-50 p-4"><p className="text-xs text-muted-foreground">Churn observé</p><p className="mt-1 text-2xl font-semibold text-slate-950">{data.churnRate.toFixed(1)} %</p><p className="mt-1 text-xs text-muted-foreground">Abonnements résiliés sur le portefeuille connu</p></div></CardContent></Card>
        <Card className="soft-card"><CardHeader><CardTitle className="text-base">Automatisation quotidienne</CardTitle></CardHeader><CardContent><div className="flex items-center gap-3"><div className={`rounded-xl p-2.5 ${automation.data?.enabled ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}><RefreshCw className="h-5 w-5" /></div><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{automation.data?.enabled ? "Active à 06:00 UTC" : "Prête à être activée"}</p><p className="text-xs leading-5 text-muted-foreground">Recalcule les scores et crée les alertes sans doublon.</p></div>{canWrite ? <Button variant={automation.data?.enabled ? "outline" : "default"} size="sm" onClick={toggleAutomation} disabled={enable.isPending || disable.isPending}>{automation.data?.enabled ? "Désactiver" : "Activer"}</Button> : null}</div>{automation.data?.lastRunAt ? <p className="mt-3 text-xs text-muted-foreground">Dernier calcul : {formatDate(automation.data.lastRunAt, true)}</p> : null}</CardContent></Card></div>
    </div>

    <div className="mt-5 grid gap-5 lg:grid-cols-2"><Card className="soft-card"><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle className="text-base">Comptes à accompagner</CardTitle><p className="mt-1 text-xs text-muted-foreground">Priorisés selon le health score</p></div><Button variant="ghost" size="sm" className="text-teal-700" onClick={() => setLocation("/clients/liste")}>Tous les clients <ArrowRight className="ml-1 h-4 w-4" /></Button></CardHeader><CardContent className="space-y-2">{data.customersAtRisk.map(customer => <button key={customer.organizationId} onClick={() => setLocation(`/clients/${customer.organizationId}`)} className="flex w-full items-center gap-3 rounded-xl p-3 text-left hover:bg-slate-50"><div className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100 text-sm font-bold text-[#123653]">{customer.healthScore}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{customer.organizationName}</p><p className="truncate text-xs text-muted-foreground">{customer.healthReasons[0]}</p></div><StatusBadge value={customer.healthLabel} /></button>)}</CardContent></Card>
      <Card className="soft-card"><CardHeader><CardTitle className="text-base">Renouvellements à venir</CardTitle><p className="text-xs text-muted-foreground">Échéances dans les 90 prochains jours</p></CardHeader><CardContent className="space-y-2">{data.renewals.length ? data.renewals.map(customer => <button key={customer.organizationId} onClick={() => setLocation(`/clients/${customer.organizationId}`)} className="flex w-full items-center gap-3 rounded-xl border border-slate-100 p-3 text-left hover:bg-slate-50"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{customer.organizationName}</p><p className="text-xs text-muted-foreground">{customer.planName} · {formatDate(customer.renewalDate)}</p></div><span className={`text-sm font-semibold ${Number(customer.daysUntilRenewal) <= 30 ? "text-rose-700" : "text-amber-700"}`}>J-{customer.daysUntilRenewal}</span></button>) : <p className="py-8 text-center text-sm text-muted-foreground">Aucune échéance à moins de 90 jours.</p>}</CardContent></Card></div>
    {subscriptionOpen ? <SubscriptionDialog open={subscriptionOpen} onOpenChange={setSubscriptionOpen} /> : null}
  </div>;
}

function HealthLine({ label, count, total, color }: { label: string; count: number; total: number; color: string }) { const percent = total ? Math.round((count / total) * 100) : 0; return <div><div className="mb-2 flex items-center justify-between text-sm"><span className="font-medium text-slate-700">{label}</span><span className="font-semibold text-slate-950">{count}</span></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${color}`} style={{ width: `${percent}%` }} /></div></div>; }
function DashboardSkeleton() { return <div className="mx-auto max-w-[1500px] space-y-5"><Skeleton className="h-24" /><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{[1,2,3,4].map(i => <Skeleton key={i} className="h-32" />)}</div><div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><Skeleton className="h-96" /><Skeleton className="h-96" /></div></div>; }
