import { canWriteCrm, EmptyState, formatCurrency, formatDate, labelFor, PageHeader, StatusBadge, STAGES } from "@/components/crm/Common";
import { DealDialog, DeleteDialog, FollowUpDialog, InteractionDialog, QuoteDialog } from "@/components/crm/Forms";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { Building2, CalendarCheck, CalendarDays, Check, CircleDollarSign, Clock3, FileSignature, Mail, MessageSquareText, Pencil, Phone, Plus, Trash2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

const eventStyle: Record<string, { icon: any; className: string }> = {
  Appel: { icon: Phone, className: "bg-sky-50 text-sky-700" },
  Email: { icon: Mail, className: "bg-violet-50 text-violet-700" },
  Reunion: { icon: CalendarCheck, className: "bg-teal-50 text-teal-700" },
  Note: { icon: MessageSquareText, className: "bg-slate-100 text-slate-600" },
};

export default function DealDetail({ id }: { id: number }) {
  const [, setLocation] = useLocation(); const utils = trpc.useUtils(); const query = trpc.crm.deals.get.useQuery({ id }); const profile = trpc.crm.profile.useQuery(); const canWrite = canWriteCrm(profile.data?.role);
  const [dialog, setDialog] = useState<"edit" | "delete" | "interaction" | "quote" | "followup" | null>(null);
  const move = trpc.crm.deals.move.useMutation(); const remove = trpc.crm.deals.delete.useMutation(); const deleteInteraction = trpc.crm.interactions.delete.useMutation(); const updateQuote = trpc.crm.quotes.updateStatus.useMutation(); const deleteQuote = trpc.crm.quotes.delete.useMutation(); const completeFollowUp = trpc.crm.followUps.complete.useMutation(); const deleteFollowUp = trpc.crm.followUps.delete.useMutation();
  const refresh = async () => Promise.all([utils.crm.deals.get.invalidate({ id }), utils.crm.deals.list.invalidate(), utils.crm.dashboard.invalidate(), utils.crm.organizations.invalidate()]);
  if (query.isLoading) return <div className="mx-auto max-w-[1400px] space-y-5"><Skeleton className="h-24" /><div className="grid gap-5 lg:grid-cols-[1.2fr_.8fr]"><Skeleton className="h-[550px]" /><Skeleton className="h-[550px]" /></div></div>;
  if (!query.data) return <EmptyState icon={CircleDollarSign} title="Opportunité introuvable" description="Cette opportunité n’existe plus ou n’est pas accessible." />;
  const { deal, interactions, quotes, followUps, contacts } = query.data;
  const changeStage = async (stage: typeof STAGES[number]) => { try { await move.mutateAsync({ id, stage }); await refresh(); toast.success(`Étape mise à jour : ${labelFor(stage)}`); } catch (error) { toast.error(error instanceof Error ? error.message : "Mise à jour impossible"); } };
  const confirmDelete = async () => { try { await remove.mutateAsync({ id }); await refresh(); toast.success("Opportunité supprimée"); setLocation("/pipeline"); } catch (error) { toast.error(error instanceof Error ? error.message : "Suppression impossible"); } };
  return <div className="reveal mx-auto max-w-[1400px]"><PageHeader backTo="/pipeline" eyebrow="Opportunité commerciale" title={deal.title} description={`${deal.organizationName} · ${deal.ownerName || "Non assignée"}`} />
    <div className="mb-5 flex flex-wrap items-center gap-2"><StatusBadge value={deal.stage} />{canWrite ? <><select value={deal.stage} onChange={event => void changeStage(event.target.value as typeof STAGES[number])} className="h-9 rounded-lg border border-slate-200 bg-white px-3 text-xs font-semibold outline-none focus:border-teal-600">{STAGES.map(stage => <option key={stage} value={stage}>{labelFor(stage)}</option>)}</select><Button variant="outline" size="sm" className="bg-white" onClick={() => setDialog("edit")}><Pencil className="mr-2 h-4 w-4" />Modifier</Button><Button variant="ghost" size="sm" className="text-rose-600" onClick={() => setDialog("delete")}><Trash2 className="mr-2 h-4 w-4" />Supprimer</Button></> : null}</div>
    <div className="grid gap-5 lg:grid-cols-[1.22fr_.78fr]">
      <Card className="soft-card"><CardHeader className="flex flex-row items-start justify-between gap-4"><div><CardTitle className="text-base">Journal des interactions</CardTitle><p className="mt-1 text-xs text-muted-foreground">Historique commercial chronologique</p></div>{canWrite ? <Button size="sm" onClick={() => setDialog("interaction")}><Plus className="mr-1 h-4 w-4" />Ajouter</Button> : null}</CardHeader><CardContent>{interactions.length ? <div className="relative space-y-5 before:absolute before:bottom-4 before:left-5 before:top-4 before:w-px before:bg-slate-200">{interactions.map(item => { const style = eventStyle[item.type] || eventStyle.Note; const Icon = style.icon; return <div key={item.id} className="group relative flex gap-4"><div className={`z-10 flex h-10 w-10 shrink-0 items-center justify-center rounded-full border-4 border-white ${style.className}`}><Icon className="h-4 w-4" /></div><div className="min-w-0 flex-1 rounded-xl border border-slate-100 bg-slate-50/60 p-4"><div className="flex flex-wrap items-start justify-between gap-2"><div><p className="text-xs font-bold uppercase tracking-wide text-slate-700">{labelFor(item.type)}</p><p className="mt-1 text-xs text-muted-foreground">{item.contactName || "Sans contact associé"} · {item.authorName || "Équipe Medactio"}</p></div><div className="flex items-center gap-1"><span className="text-xs text-muted-foreground">{formatDate(item.occurredAt, true)}</span>{canWrite ? <Button variant="ghost" size="icon" className="h-7 w-7 text-rose-500 opacity-100 sm:opacity-0 sm:group-hover:opacity-100" onClick={async () => { try { await deleteInteraction.mutateAsync({ id: item.id }); await refresh(); toast.success("Interaction supprimée"); } catch { toast.error("Suppression impossible"); } }}><Trash2 className="h-3.5 w-3.5" /></Button> : null}</div></div><p className="mt-3 text-sm leading-6 text-slate-700">{item.content}</p></div></div>; })}</div> : <EmptyState icon={MessageSquareText} title="Aucune interaction" description="Ajoutez le premier appel, email, rendez-vous ou commentaire lié à cette opportunité." actionLabel={canWrite ? "Ajouter une interaction" : undefined} onAction={() => setDialog("interaction")} />}</CardContent></Card>
      <div className="space-y-5"><Card className="soft-card"><CardHeader><CardTitle className="text-base">Synthèse</CardTitle></CardHeader><CardContent className="space-y-5"><button onClick={() => setLocation(`/organisations/${deal.organizationId}`)} className="flex w-full gap-3 text-left"><IconBox icon={Building2} /><div><p className="text-xs text-muted-foreground">Organisation</p><p className="mt-0.5 text-sm font-semibold text-teal-700">{deal.organizationName}</p></div></button><Info icon={CircleDollarSign} label="Montant estimé" value={formatCurrency(deal.amount)} /><Info icon={CalendarDays} label="Clôture estimée" value={formatDate(deal.expectedCloseDate)} /><Info icon={Clock3} label="Créée le" value={formatDate(deal.createdAt)} />{deal.notes ? <div className="rounded-xl bg-slate-50 p-4"><p className="text-xs font-semibold text-muted-foreground">Notes</p><p className="mt-2 text-sm leading-6 text-slate-700">{deal.notes}</p></div> : null}{deal.lossReason ? <div className="rounded-xl bg-rose-50 p-4"><p className="text-xs font-semibold text-rose-700">Motif de perte</p><p className="mt-2 text-sm leading-6 text-rose-800">{deal.lossReason}</p></div> : null}</CardContent></Card>
        <Card className="soft-card"><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle className="flex items-center gap-2 text-base"><FileSignature className="h-4 w-4 text-teal-700" /> Devis</CardTitle><p className="mt-1 text-xs text-muted-foreground">Création et suivi de signature</p></div>{canWrite ? <Button variant="outline" size="sm" className="bg-white" onClick={() => setDialog("quote")}><Plus className="mr-1 h-4 w-4" />Créer</Button> : null}</CardHeader><CardContent>{quotes.length ? <div className="space-y-2">{quotes.map(quote => <div key={quote.id} className="group rounded-xl border border-slate-100 p-3"><div className="flex items-center gap-3"><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{quote.quoteNumber}</p><p className="text-xs text-muted-foreground">{formatCurrency(quote.amount)} · valide jusqu’au {formatDate(quote.validUntil)}</p></div>{canWrite ? <select value={quote.status} onChange={async event => { try { await updateQuote.mutateAsync({ id: quote.id, status: event.target.value as any }); await refresh(); toast.success("Statut du devis mis à jour"); } catch { toast.error("Mise à jour impossible"); } }} className="h-8 rounded-lg border border-slate-200 bg-white px-2 text-xs">{["Brouillon", "Envoye", "Vu", "Signe", "Expire", "Refuse"].map(status => <option key={status} value={status}>{labelFor(status)}</option>)}</select> : <StatusBadge value={quote.status} />}{canWrite ? <Button variant="ghost" size="icon" className="h-8 w-8 text-rose-500 opacity-100 sm:opacity-0 sm:group-hover:opacity-100" onClick={async () => { await deleteQuote.mutateAsync({ id: quote.id }); await refresh(); toast.success("Devis supprimé"); }}><Trash2 className="h-3.5 w-3.5" /></Button> : null}</div></div>)}</div> : <p className="py-4 text-center text-sm text-muted-foreground">Aucun devis créé.</p>}</CardContent></Card>
        <Card className="soft-card"><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle className="flex items-center gap-2 text-base"><Clock3 className="h-4 w-4 text-amber-600" /> Relances</CardTitle><p className="mt-1 text-xs text-muted-foreground">Échéances planifiées</p></div>{canWrite ? <Button variant="outline" size="sm" className="bg-white" onClick={() => setDialog("followup")}><Plus className="mr-1 h-4 w-4" />Programmer</Button> : null}</CardHeader><CardContent>{followUps.length ? <div className="space-y-2">{followUps.map(item => <div key={item.id} className={`group flex items-start gap-3 rounded-xl border p-3 ${item.status === "Effectuee" ? "border-emerald-100 bg-emerald-50/40" : "border-slate-100"}`}><div className="min-w-0 flex-1"><p className="text-sm font-semibold">{labelFor(item.type)}</p><p className="text-xs text-muted-foreground">{formatDate(item.dueAt, true)}{item.note ? ` · ${item.note}` : ""}</p></div>{item.status === "Effectuee" ? <StatusBadge value="Effectuee" /> : canWrite ? <Button variant="outline" size="icon" className="h-8 w-8 bg-white text-emerald-700" title="Marquer comme effectuée" onClick={async () => { await completeFollowUp.mutateAsync({ id: item.id }); await refresh(); toast.success("Relance effectuée"); }}><Check className="h-4 w-4" /></Button> : null}{canWrite ? <Button variant="ghost" size="icon" className="h-8 w-8 text-rose-500 opacity-100 sm:opacity-0 sm:group-hover:opacity-100" onClick={async () => { await deleteFollowUp.mutateAsync({ id: item.id }); await refresh(); toast.success("Relance supprimée"); }}><Trash2 className="h-3.5 w-3.5" /></Button> : null}</div>)}</div> : <p className="py-4 text-center text-sm text-muted-foreground">Aucune relance programmée.</p>}</CardContent></Card>
      </div>
    </div>
    {dialog === "edit" ? <DealDialog open onOpenChange={() => setDialog(null)} initial={deal} /> : null}{dialog === "delete" ? <DeleteDialog open onOpenChange={() => setDialog(null)} title="Supprimer cette opportunité ?" description="Les interactions, devis et relances associés seront supprimés." onConfirm={confirmDelete} pending={remove.isPending} /> : null}{dialog === "interaction" ? <InteractionDialog open onOpenChange={() => setDialog(null)} dealId={id} contacts={contacts} /> : null}{dialog === "quote" ? <QuoteDialog open onOpenChange={() => setDialog(null)} dealId={id} defaultAmount={deal.amount} /> : null}{dialog === "followup" ? <FollowUpDialog open onOpenChange={() => setDialog(null)} dealId={id} /> : null}
  </div>;
}

function IconBox({ icon: Icon }: { icon: any }) { return <div className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-slate-100 text-slate-500"><Icon className="h-4 w-4" /></div>; }
function Info({ icon: Icon, label, value }: { icon: any; label: string; value: string }) { return <div className="flex gap-3"><IconBox icon={Icon} /><div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-0.5 text-sm font-semibold text-slate-900">{value}</p></div></div>; }
