import { DirectionGate, formatNumber, formatPercent, InsightCard, PeriodSelector, shortCurrency, type AnalyticsPeriod } from "@/components/crm/Analytics";
import { PageHeader } from "@/components/crm/Common";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { trpc } from "@/lib/trpc";
import { ArrowRight, BarChart3, Bot, CircleDollarSign, Download, Headphones, HeartPulse, Megaphone, Target, UsersRound } from "lucide-react";
import { useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Legend, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useLocation } from "wouter";

type Pole = "commercial" | "clients" | "support" | "marketing";
const config = {
  commercial: { eyebrow: "Reporting Commercial", title: "Croissance & conversion", description: "Suivez la création de revenu, la maturité du pipeline et la performance de chaque commercial.", icon: Target },
  clients: { eyebrow: "Reporting Clients & Licences", title: "Revenu récurrent & adoption", description: "Mesurez la base installée, la fidélisation, l’usage produit et l’économie unitaire SaaS.", icon: HeartPulse },
  support: { eyebrow: "Reporting Support", title: "Qualité de service & efficacité", description: "Analysez le volume traité, les délais de résolution et la charge de chaque collaborateur.", icon: Headphones },
  marketing: { eyebrow: "Reporting Marketing", title: "Acquisition & efficacité", description: "Reliez budgets, campagnes, leads générés et contribution à l’acquisition client.", icon: Megaphone },
};
const tooltipStyle = { borderRadius: 12, border: "1px solid #e2e8f0", boxShadow: "0 8px 24px rgba(15,23,42,.08)", fontSize: 12 };

export default function DirectionReport({ pole }: { pole: Pole }) {
  const [, setLocation] = useLocation(); const [period, setPeriod] = useState<AnalyticsPeriod>("12m"); const query = trpc.analytics.dashboard.useQuery({ period }, { retry: false }); const data = query.data; const page = config[pole];
  return <DirectionGate loading={query.isLoading} forbidden={!!query.error}><div className="space-y-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><PageHeader backTo="/direction" eyebrow={page.eyebrow} title={page.title} description={page.description} /><div className="flex flex-wrap gap-2"><PeriodSelector value={period} onChange={setPeriod} /><Button onClick={() => setLocation("/direction/exports")} className="bg-[#123653]"><Download className="mr-2 h-4 w-4" />Exporter</Button></div></div>{data && <>{pole === "commercial" && <Commercial data={data} />}{pole === "clients" && <Clients data={data} />}{pole === "support" && <Support data={data} />}{pole === "marketing" && <Marketing data={data} />}</>}</div></DirectionGate>;
}

function Commercial({ data }: { data: any }) {
  return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><InsightCard title="CA gagné" value={shortCurrency(data.commercial.wonRevenue)} detail="Deals gagnés sur la période" /><InsightCard title="Pipeline pondéré" value={shortCurrency(data.commercial.weightedPipeline)} detail={`${shortCurrency(data.commercial.totalPipeline)} de pipeline brut`} accent="amber" /><InsightCard title="Conversion" value={formatPercent(data.commercial.conversionRate)} detail={`${data.commercial.activeDeals} opportunités encore actives`} accent="blue" /><InsightCard title="À encaisser" value={shortCurrency(data.cash.expectedCollections)} detail={`${data.cash.overdueInvoices} facture(s) en retard`} accent={data.cash.overdueInvoices ? "rose" : "teal"} /></div><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><ChartCard title="Revenu gagné et encaissé"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.monthly}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" axisLine={false} tickLine={false} /><YAxis axisLine={false} tickLine={false} tickFormatter={(value: number) => `${Math.round(value / 1000)}k`} /><Tooltip contentStyle={tooltipStyle} /><Legend /><Area type="monotone" dataKey="wonRevenue" name="CA gagné" stroke="#f59e0b" fill="#fef3c7" strokeWidth={2.5} /><Area type="monotone" dataKey="collected" name="Encaissé" stroke="#0d9488" fill="#ccfbf1" strokeWidth={2.5} /></AreaChart></ResponsiveContainer></ChartCard><Performance title="Performance commerciale" rows={data.performance.commercial} currencyValue /></div></>;
}
function Clients({ data }: { data: any }) {
  return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><InsightCard title="MRR" value={shortCurrency(data.saas.mrr)} detail={`ARR ${shortCurrency(data.saas.arr)}`} /><InsightCard title="Churn" value={formatPercent(data.saas.churnRate)} detail="Taux annualisé sur la période" accent={data.saas.churnRate > 10 ? "rose" : "teal"} /><InsightCard title="CAC" value={data.saas.cac === null ? "—" : shortCurrency(data.saas.cac)} detail="Budget marketing / nouveaux clients" accent="amber" /><InsightCard title="LTV indicative" value={data.saas.ltv === null ? "—" : shortCurrency(data.saas.ltv)} detail={`Marge brute retenue : ${data.saas.grossMarginAssumption} %`} accent="blue" /></div><div className="grid gap-5 xl:grid-cols-[1.25fr_.75fr]"><ChartCard title="Adoption de la solution"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.monthly}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" axisLine={false} tickLine={false} /><YAxis axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltipStyle} /><Legend /><Bar dataKey="documents" name="Écrits" fill="#0d9488" radius={[5,5,0,0]} /><Bar dataKey="aiRequests" name="Requêtes IA" fill="#7c3aed" radius={[5,5,0,0]} /></BarChart></ResponsiveContainer></ChartCard><Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-lg">Santé du portefeuille</CardTitle></CardHeader><CardContent className="space-y-5"><PortfolioRow label="Clients actifs" value={data.saas.activeCustomers} total={data.saas.activeCustomers} color="bg-teal-500" /><PortfolioRow label="À surveiller" value={data.saas.monitoredCustomers} total={data.saas.activeCustomers} color="bg-amber-500" /><PortfolioRow label="À risque" value={data.saas.atRiskCustomers} total={data.saas.activeCustomers} color="bg-rose-500" /><div className="rounded-xl bg-violet-50 p-4"><Bot className="h-5 w-5 text-violet-600" /><p className="mt-3 text-2xl font-semibold text-violet-900">{formatNumber(data.usage.aiRequests30)}</p><p className="text-xs text-violet-700">requêtes IA sur 30 jours · {formatPercent(data.usage.aiRequestsTrend)} d’évolution</p></div></CardContent></Card></div></>;
}
function Support({ data }: { data: any }) {
  return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><InsightCard title="Tickets créés" value={String(data.support.ticketsCreated)} detail="Sur la période sélectionnée" /><InsightCard title="Tickets résolus" value={String(data.support.ticketsResolved)} detail={`${formatPercent(data.support.resolutionRate)} de résolution`} accent="blue" /><InsightCard title="Temps moyen" value={`${data.support.averageResolutionHours} h`} detail="Du ticket à sa résolution" accent="amber" /><InsightCard title="SLA dépassés" value={String(data.support.slaBreaches)} detail={`${data.support.openTickets} tickets encore ouverts`} accent={data.support.slaBreaches ? "rose" : "teal"} /></div><div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]"><Card className="border-0 bg-[#123653] text-white shadow-sm"><CardContent className="p-6"><UsersRound className="h-7 w-7 text-teal-300" /><p className="mt-5 text-sm text-slate-300">Taux de résolution</p><p className="mt-2 text-4xl font-semibold">{formatPercent(data.support.resolutionRate)}</p><Progress value={data.support.resolutionRate} className="mt-5 h-2 bg-white/15" /><p className="mt-5 text-sm leading-6 text-slate-300">La cible de pilotage recommandée est supérieure à 90 %, avec zéro dépassement SLA sur les demandes urgentes.</p></CardContent></Card><Performance title="Performance Support" rows={data.performance.support} /></div></>;
}
function Marketing({ data }: { data: any }) {
  return <><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><InsightCard title="Budget engagé" value={shortCurrency(data.marketing.spend)} detail="Sur la période sélectionnée" /><InsightCard title="Leads générés" value={formatNumber(data.marketing.leadsGenerated)} detail={`${data.marketing.campaigns} campagnes analysées`} accent="blue" /><InsightCard title="Coût par lead" value={data.marketing.costPerLead === null ? "—" : shortCurrency(data.marketing.costPerLead)} detail="Budget / leads générés" accent="amber" /><InsightCard title="ROI Marketing" value={data.marketing.roi === null ? "—" : formatPercent(data.marketing.roi)} detail={`${shortCurrency(data.marketing.attributedRevenue)} de revenu attribué`} accent="teal" /></div><div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><ChartCard title="Contribution marketing à la croissance"><ResponsiveContainer width="100%" height="100%"><LineChart data={data.monthly}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="label" axisLine={false} tickLine={false} /><YAxis axisLine={false} tickLine={false} /><Tooltip contentStyle={tooltipStyle} /><Legend /><Line type="monotone" dataKey="mrr" name="MRR" stroke="#0d9488" strokeWidth={3} dot={false} /><Line type="monotone" dataKey="wonRevenue" name="CA gagné" stroke="#7c3aed" strokeWidth={2.5} dot={false} /></LineChart></ResponsiveContainer></ChartCard><Performance title="Performance Marketing" rows={data.performance.marketing} /></div></>;
}
function ChartCard({ title, children }: { title: string; children: React.ReactNode }) { return <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><BarChart3 className="h-5 w-5 text-teal-600" />{title}</CardTitle></CardHeader><CardContent><div className="h-80">{children}</div></CardContent></Card>; }
function PortfolioRow({ label, value, total, color }: { label: string; value: number; total: number; color: string }) { const percentage = total ? value / total * 100 : 0; return <div><div className="mb-2 flex items-center justify-between text-sm"><span>{label}</span><strong>{value}</strong></div><div className="h-2 overflow-hidden rounded-full bg-slate-100"><div className={`h-full rounded-full ${color}`} style={{ width: `${percentage}%` }} /></div></div>; }
function Performance({ title, rows, currencyValue = false }: { title: string; rows: any[]; currencyValue?: boolean }) { return <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-lg">{title}</CardTitle></CardHeader><CardContent className="space-y-3">{rows.length ? rows.map((row, index) => <div key={row.name} className="flex items-center gap-4 rounded-xl bg-slate-50 p-3"><div className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-white text-sm font-semibold shadow-sm">{index + 1}</div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{row.name}</p><p className="text-xs text-muted-foreground">{row.primary} {row.primaryLabel} · {row.secondary} {row.secondaryLabel}</p></div><div className="text-right"><p className="text-sm font-semibold">{currencyValue ? shortCurrency(row.value) : formatNumber(row.value)}</p><p className="text-[11px] text-muted-foreground">{row.valueLabel}</p></div></div>) : <div className="py-10 text-center text-sm text-muted-foreground">Aucune donnée sur cette période.</div>}</CardContent></Card>; }
