import { DirectionGate, ExecutiveMetric, formatNumber, formatPercent, InsightCard, PeriodSelector, shortCurrency, type AnalyticsPeriod } from "@/components/crm/Analytics";
import { PageHeader } from "@/components/crm/Common";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { Activity, ArrowRight, Bot, Building2, CircleDollarSign, CreditCard, Gauge, HeartPulse, ReceiptText, Target, UsersRound } from "lucide-react";
import { useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Legend, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useLocation } from "wouter";

const tooltipStyle = { borderRadius: 12, border: "1px solid #e2e8f0", boxShadow: "0 8px 24px rgba(15,23,42,.08)", fontSize: 12 };

export default function DirectionDashboard() {
  const [, setLocation] = useLocation(); const [period, setPeriod] = useState<AnalyticsPeriod>("12m"); const query = trpc.analytics.dashboard.useQuery({ period }, { retry: false }); const data = query.data;
  return <DirectionGate loading={query.isLoading} forbidden={!!query.error}><div className="space-y-7">
    <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><PageHeader eyebrow="Pôle Direction & Analytics" title="La santé de Medactio, en un regard." description="Pilotez la croissance récurrente, l’adoption, la performance des équipes et les encaissements depuis une source unique." /><PeriodSelector value={period} onChange={setPeriod} /></div>
    {data && <>
      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <ExecutiveMetric label="Revenu mensuel récurrent" value={shortCurrency(data.saas.mrr)} detail={`ARR ${shortCurrency(data.saas.arr)}`} icon={CircleDollarSign} tone="navy" />
        <ExecutiveMetric label="Clients actifs" value={formatNumber(data.saas.activeCustomers)} detail={`${data.saas.atRiskCustomers} à risque · ${data.saas.monitoredCustomers} à surveiller`} icon={Building2} tone="teal" />
        <ExecutiveMetric label="Écrits générés — 30 j" value={formatNumber(data.usage.documents30)} detail={`${formatNumber(data.usage.aiRequests30)} requêtes IA`} icon={Bot} tone="violet" trend={data.usage.documentsTrend} />
        <ExecutiveMetric label="Pipeline pondéré" value={shortCurrency(data.commercial.weightedPipeline)} detail={`${data.commercial.activeDeals} opportunités actives`} icon={Target} tone="amber" />
      </div>
      <div className="grid gap-5 xl:grid-cols-[1.35fr_.65fr]">
        <Card className="border-0 shadow-sm"><CardHeader className="flex-row items-center justify-between"><div><CardTitle className="text-lg">Trajectoire du revenu récurrent</CardTitle><p className="mt-1 text-xs text-muted-foreground">MRR reconstitué sur les douze derniers mois</p></div><Gauge className="h-5 w-5 text-teal-600" /></CardHeader><CardContent><div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data.monthly}><defs><linearGradient id="mrrGradient" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#0d9488" stopOpacity={0.32} /><stop offset="100%" stopColor="#0d9488" stopOpacity={0.02} /></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e8edf1" /><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: "#64748b" }} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: "#64748b" }} tickFormatter={value => `${Math.round(value / 1000)}k`} /><Tooltip contentStyle={tooltipStyle} formatter={(value: number) => [shortCurrency(value), "MRR"]} /><Area type="monotone" dataKey="mrr" stroke="#0d9488" strokeWidth={3} fill="url(#mrrGradient)" /></AreaChart></ResponsiveContainer></div></CardContent></Card>
        <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-1"><InsightCard title="Churn annualisé" value={formatPercent(data.saas.churnRate)} detail="Résiliations observées sur la période sélectionnée." accent={data.saas.churnRate > 10 ? "rose" : "teal"} /><InsightCard title="CAC estimé" value={data.saas.cac === null ? "Non disponible" : shortCurrency(data.saas.cac)} detail="Budget marketing rapporté aux nouveaux clients gagnés." accent="amber" /><InsightCard title="LTV indicative" value={data.saas.ltv === null ? "Non calculable" : shortCurrency(data.saas.ltv)} detail={`Marge brute conventionnelle de ${data.saas.grossMarginAssumption} %.`} accent="blue" /></div>
      </div>
      <div className="grid gap-5 xl:grid-cols-[.8fr_1.2fr]">
        <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-lg">Encaissements & exposition</CardTitle></CardHeader><CardContent className="space-y-4"><div className="rounded-2xl bg-emerald-50 p-4"><div className="flex items-center justify-between"><span className="text-sm font-medium text-emerald-900">Encaissé sur la période</span><CreditCard className="h-5 w-5 text-emerald-600" /></div><p className="mt-2 text-3xl font-semibold text-emerald-800">{shortCurrency(data.cash.collectedRevenue)}</p></div><div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-slate-50 p-3"><p className="text-xs text-muted-foreground">À encaisser</p><p className="mt-1 text-lg font-semibold">{shortCurrency(data.cash.expectedCollections)}</p></div><div className="rounded-xl bg-rose-50 p-3"><p className="text-xs text-rose-600">En retard</p><p className="mt-1 text-lg font-semibold text-rose-700">{shortCurrency(data.cash.overdueAmount)}</p></div></div><Button variant="outline" onClick={() => setLocation("/direction/commercial")} className="w-full bg-white">Analyser pipeline & cash <ArrowRight className="ml-2 h-4 w-4" /></Button></CardContent></Card>
        <Card className="border-0 shadow-sm"><CardHeader><div className="flex items-center justify-between"><div><CardTitle className="text-lg">Volume d’utilisation</CardTitle><p className="mt-1 text-xs text-muted-foreground">Écrits générés et requêtes IA par mois</p></div><Activity className="h-5 w-5 text-violet-600" /></div></CardHeader><CardContent><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.monthly}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#e8edf1" /><XAxis dataKey="label" axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: "#64748b" }} /><YAxis axisLine={false} tickLine={false} tick={{ fontSize: 11, fill: "#64748b" }} /><Tooltip contentStyle={tooltipStyle} /><Legend wrapperStyle={{ fontSize: 12 }} /><Bar dataKey="documents" name="Écrits" fill="#0d9488" radius={[4,4,0,0]} /><Bar dataKey="aiRequests" name="Requêtes IA" fill="#7c3aed" radius={[4,4,0,0]} /></BarChart></ResponsiveContainer></div></CardContent></Card>
      </div>
      <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
        {[{ title: "Commercial", value: shortCurrency(data.commercial.wonRevenue), detail: `${formatPercent(data.commercial.conversionRate)} de conversion`, icon: Target, path: "/direction/commercial", color: "text-amber-600 bg-amber-50" }, { title: "Clients & licences", value: shortCurrency(data.saas.mrr), detail: `${data.saas.activeCustomers} comptes actifs`, icon: HeartPulse, path: "/direction/clients", color: "text-teal-700 bg-teal-50" }, { title: "Support", value: `${data.support.ticketsResolved} résolus`, detail: `${data.support.slaBreaches} SLA dépassés`, icon: UsersRound, path: "/direction/support", color: "text-sky-700 bg-sky-50" }, { title: "Marketing", value: `${data.marketing.leadsGenerated} leads`, detail: `${data.marketing.campaigns} campagnes`, icon: ReceiptText, path: "/direction/marketing", color: "text-violet-700 bg-violet-50" }].map(pole => <button key={pole.title} onClick={() => setLocation(pole.path)} className="group rounded-2xl bg-white p-5 text-left shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><div className={`inline-flex rounded-xl p-2.5 ${pole.color}`}><pole.icon className="h-5 w-5" /></div><p className="mt-4 text-sm font-semibold text-slate-500">{pole.title}</p><p className="mt-1 text-xl font-semibold text-slate-950">{pole.value}</p><div className="mt-3 flex items-center justify-between text-xs text-muted-foreground"><span>{pole.detail}</span><ArrowRight className="h-4 w-4 transition group-hover:translate-x-1" /></div></button>)}
      </div>
    </>}
  </div></DirectionGate>;
}
