import { canWriteInvoices, EmptyState, formatCurrency, formatDate, labelFor, PageHeader, StatusBadge } from "@/components/crm/Common";
import { DeleteDialog } from "@/components/crm/Forms";
import { InvoiceDialog } from "@/components/crm/SupportForms";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { CheckCircle2, Loader2, Mail, Pencil, ReceiptText, Search, ShieldX, Trash2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function Invoices() {
  const utils = trpc.useUtils(); const profile = trpc.support.profile.useQuery(); const [search, setSearch] = useState(""); const [status, setStatus] = useState("Tous"); const [dialog, setDialog] = useState<{ open: boolean; item?: any }>({ open: false }); const [deleting, setDeleting] = useState<any>(null);
  const query = trpc.support.invoices.list.useQuery({ search, status }, { retry: false }); const update = trpc.support.invoices.update.useMutation(); const remind = trpc.support.invoices.remind.useMutation(); const remove = trpc.support.invoices.delete.useMutation(); const canWrite = canWriteInvoices(profile.data?.role);
  const markPaid = async (invoice: any) => { try { await update.mutateAsync({ id: invoice.id, status: "Payee", paidAt: new Date().toISOString().slice(0, 10) }); await Promise.all([query.refetch(), utils.support.dashboard.invalidate()]); toast.success("Paiement enregistré"); } catch (error) { toast.error(error instanceof Error ? error.message : "Mise à jour impossible"); } };
  const sendReminder = async (invoice: any) => { try { await remind.mutateAsync({ id: invoice.id }); await Promise.all([query.refetch(), utils.support.dashboard.invalidate()]); toast.success("Relance enregistrée et prochaine relance planifiée à J+7"); } catch (error) { toast.error(error instanceof Error ? error.message : "Relance impossible"); } };
  const confirmDelete = async () => { if (!deleting) return; await remove.mutateAsync({ id: deleting.id }); await Promise.all([query.refetch(), utils.support.dashboard.invalidate()]); setDeleting(null); toast.success("Facture supprimée"); };
  const rows = query.data || []; const outstanding = rows.filter(row => !["Brouillon", "Payee"].includes(row.status)).reduce((sum, row) => sum + Number(row.amount), 0); const paid = rows.filter(row => row.status === "Payee").reduce((sum, row) => sum + Number(row.amount), 0);
  return <div><PageHeader eyebrow="Secrétariat & Support" title="Suivi de facturation" description="Centralisez les factures émises, paiements reçus et relances d’impayés." actionLabel={canWrite ? "Nouvelle facture" : undefined} onAction={() => setDialog({ open: true })} />
    {query.error ? <div className="flex min-h-72 flex-col items-center justify-center rounded-2xl bg-white p-8 text-center shadow-sm"><ShieldX className="mb-3 h-8 w-8 text-slate-400" /><h2 className="font-semibold">Accès financier restreint</h2><p className="mt-2 max-w-md text-sm text-muted-foreground">La facturation est réservée à l’administration, la direction, au secrétariat et à la finance.</p></div> : <>
      <div className="mb-5 grid gap-4 sm:grid-cols-3"><Card className="border-0 shadow-sm"><CardContent className="p-5"><p className="text-sm text-muted-foreground">Montant émis</p><p className="mt-2 text-2xl font-semibold">{formatCurrency(rows.reduce((sum, row) => sum + Number(row.amount), 0))}</p></CardContent></Card><Card className="border-0 shadow-sm"><CardContent className="p-5"><p className="text-sm text-muted-foreground">À encaisser</p><p className="mt-2 text-2xl font-semibold text-amber-700">{formatCurrency(outstanding)}</p></CardContent></Card><Card className="border-0 shadow-sm"><CardContent className="p-5"><p className="text-sm text-muted-foreground">Encaissé</p><p className="mt-2 text-2xl font-semibold text-emerald-700">{formatCurrency(paid)}</p></CardContent></Card></div>
      <Card className="mb-5 border-0 shadow-sm"><CardContent className="grid gap-3 p-4 md:grid-cols-[1fr_190px]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="Numéro ou établissement…" className="pl-9" /></div><select value={status} onChange={e => setStatus(e.target.value)} className="h-10 rounded-lg border bg-white px-3 text-sm">{["Tous", "Brouillon", "Envoyee", "Payee", "En Retard"].map(value => <option key={value} value={value}>{labelFor(value)}</option>)}</select></CardContent></Card>
      {query.isLoading ? <div className="flex min-h-64 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin" /></div> : rows.length ? <div className="space-y-3">{rows.map(invoice => <Card key={invoice.id} className="border-0 shadow-sm"><CardContent className="grid gap-4 p-4 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{invoice.invoiceNumber}</p><StatusBadge value={invoice.status} /></div><p className="mt-1 text-sm text-muted-foreground">{invoice.organizationName} · échéance {formatDate(invoice.dueDate)}</p><p className="mt-2 text-xs text-muted-foreground">{invoice.reminderCount} relance{invoice.reminderCount > 1 ? "s" : ""}{invoice.lastReminderAt ? ` · dernière le ${formatDate(invoice.lastReminderAt, true)}` : ""}</p></div><div className="flex flex-wrap items-center justify-between gap-2 sm:justify-end"><p className="mr-2 text-lg font-semibold">{formatCurrency(invoice.amount)}</p>{canWrite && !["Brouillon", "Payee"].includes(invoice.status) && <><Button size="sm" variant="outline" onClick={() => sendReminder(invoice)} disabled={remind.isPending}><Mail className="mr-2 h-4 w-4" />Relancer</Button><Button size="sm" onClick={() => markPaid(invoice)} className="bg-emerald-600 hover:bg-emerald-700"><CheckCircle2 className="mr-2 h-4 w-4" />Payée</Button></>} {canWrite && <><Button size="icon" variant="ghost" onClick={() => setDialog({ open: true, item: invoice })}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" className="text-rose-600" onClick={() => setDeleting(invoice)}><Trash2 className="h-4 w-4" /></Button></>}</div></CardContent></Card>)}</div> : <EmptyState icon={ReceiptText} title="Aucune facture" description="Créez la première facture client à suivre." actionLabel={canWrite ? "Nouvelle facture" : undefined} onAction={() => setDialog({ open: true })} />}
    </>}
    {dialog.open && <InvoiceDialog key={dialog.item?.id || "new"} open={dialog.open} onOpenChange={open => setDialog({ open })} initial={dialog.item} />}
    <DeleteDialog open={!!deleting} onOpenChange={open => !open && setDeleting(null)} title="Supprimer cette facture ?" description="Cette opération financière sera inscrite dans le journal d’audit." onConfirm={confirmDelete} pending={remove.isPending} />
  </div>;
}
