import { CampaignDialog, EventDialog, LeadDialog } from "@/components/crm/MarketingForms";
import { canWriteMarketing, formatCurrency, formatDate, labelFor, PageHeader, StatCard, StatusBadge } from "@/components/crm/Common";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { ArrowRight, CalendarDays, CircleDollarSign, Megaphone, MousePointerClick, Plus, Sparkles, Target, UsersRound, Video } from "lucide-react";
import { useState } from "react";
import { Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { useLocation } from "wouter";

const number = (value: number) => new Intl.NumberFormat("fr-FR").format(value);
const percent = (value: number | null) => value === null ? "—" : `${new Intl.NumberFormat("fr-FR", { maximumFractionDigits: 1 }).format(value)} %`;

export default function MarketingDashboard() {
  const [, setLocation] = useLocation(); const [campaignOpen, setCampaignOpen] = useState(false); const [leadOpen, setLeadOpen] = useState(false); const [eventOpen, setEventOpen] = useState(false);
  const dashboard = trpc.marketing.dashboard.useQuery(); const users = trpc.marketing.users.useQuery(); const profile = trpc.marketing.profile.useQuery(); const data = dashboard.data; const canWrite = canWriteMarketing(profile.data?.role);
  if (dashboard.isLoading) return <div className="space-y-5"><Skeleton className="h-28 rounded-2xl" /><div className="grid gap-4 md:grid-cols-4">{Array.from({ length: 4 }, (_, index) => <Skeleton key={index} className="h-36 rounded-2xl" />)}</div><Skeleton className="h-80 rounded-2xl" /></div>;
  if (!data) return <div className="rounded-2xl bg-white p-8 text-center text-sm text-muted-foreground">Le tableau de bord Marketing est indisponible.</div>;
  return <div className="space-y-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><PageHeader eyebrow="Pôle Marketing" title="Transformez chaque action en opportunité mesurable." description="Pilotez campagnes, leads, contenus et événements depuis un espace relié au CRM et à la Direction." /><div className="flex flex-wrap gap-2">{canWrite && <><Button variant="outline" onClick={() => setLeadOpen(true)} className="bg-white"><UsersRound className="mr-2 h-4 w-4" />Ajouter un lead</Button><Button onClick={() => setCampaignOpen(true)} className="bg-[#123653]"><Plus className="mr-2 h-4 w-4" />Nouvelle campagne</Button></>}</div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Leads capturés" value={number(data.summary.totalLeads)} detail={`${data.summary.activeCampaigns} campagnes actives`} icon={UsersRound} accent="teal" /><StatCard label="Coût par lead" value={data.summary.cpl === null ? "—" : formatCurrency(data.summary.cpl)} detail={`${formatCurrency(data.summary.totalBudget)} engagés`} icon={MousePointerClick} accent="amber" /><StatCard label="Conversion lead → client" value={percent(data.summary.conversionRate)} detail="Leads au statut converti" icon={Target} accent="violet" /><StatCard label="ROI marketing" value={percent(data.summary.roi)} detail={`${formatCurrency(data.summary.totalRevenue)} attribués`} icon={CircleDollarSign} accent="navy" /></div>
    <div className="grid gap-5 xl:grid-cols-[1.15fr_.85fr]"><Card className="border-0 shadow-sm"><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle className="text-lg">Performance par canal</CardTitle><p className="mt-1 text-sm text-muted-foreground">Budget et leads générés par source</p></div><Button variant="ghost" onClick={() => setLocation("/marketing/campagnes")} className="text-teal-700">Toutes les campagnes <ArrowRight className="ml-2 h-4 w-4" /></Button></CardHeader><CardContent><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={data.byChannel} margin={{ left: 0, right: 10 }}><CartesianGrid strokeDasharray="3 3" vertical={false} /><XAxis dataKey="channel" axisLine={false} tickLine={false} tickFormatter={labelFor} fontSize={11} /><YAxis yAxisId="leads" axisLine={false} tickLine={false} /><YAxis yAxisId="budget" orientation="right" axisLine={false} tickLine={false} tickFormatter={(value: number) => `${Math.round(value / 1000)}k`} /><Tooltip formatter={(value: number, name) => [name === "Budget" ? formatCurrency(value) : number(value), name]} /><Bar yAxisId="leads" dataKey="leads" name="Leads" fill="#14b8a6" radius={[6,6,0,0]} /><Bar yAxisId="budget" dataKey="budget" name="Budget" fill="#173f5d" radius={[6,6,0,0]} /></BarChart></ResponsiveContainer></div></CardContent></Card>
      <Card className="border-0 bg-[#123653] text-white shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Sparkles className="h-5 w-5 text-teal-300" />Cadence éditoriale</CardTitle></CardHeader><CardContent className="space-y-5"><div className="grid grid-cols-2 gap-3"><div className="rounded-xl bg-white/8 p-4"><p className="text-3xl font-semibold">{data.summary.upcomingContent}</p><p className="mt-1 text-xs text-slate-300">contenus à publier</p></div><div className="rounded-xl bg-white/8 p-4"><p className="text-3xl font-semibold">{data.summary.publishedContent}</p><p className="mt-1 text-xs text-slate-300">contenus publiés</p></div></div><div><div className="mb-2 flex justify-between text-sm"><span>Taux de présence événements</span><strong>{percent(data.summary.attendanceRate)}</strong></div><Progress value={data.summary.attendanceRate} className="h-2 bg-white/15" /></div><div><div className="mb-2 flex justify-between text-sm"><span>Présents convertis en RDV</span><strong>{percent(data.summary.eventMeetingRate)}</strong></div><Progress value={data.summary.eventMeetingRate} className="h-2 bg-white/15" /></div><Button onClick={() => setLocation("/marketing/calendrier")} variant="secondary" className="w-full">Ouvrir le calendrier</Button></CardContent></Card></div>
    <div className="grid gap-5 xl:grid-cols-2"><Card className="border-0 shadow-sm"><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="text-lg">Campagnes prioritaires</CardTitle><Megaphone className="h-5 w-5 text-teal-600" /></CardHeader><CardContent className="space-y-3">{data.campaigns.slice(0, 5).map(campaign => <button key={campaign.id} onClick={() => setLocation(`/marketing/campagnes/${campaign.id}`)} className="w-full rounded-xl bg-slate-50 p-4 text-left transition hover:bg-slate-100"><div className="flex items-start justify-between gap-3"><div><p className="font-semibold text-slate-900">{campaign.name}</p><p className="mt-1 text-xs text-muted-foreground">{labelFor(campaign.channel)} · {campaign.leadCount} leads · CPL {campaign.cpl === null ? "—" : formatCurrency(campaign.cpl)}</p></div><StatusBadge value={campaign.status} /></div><div className="mt-3 flex items-center gap-3"><Progress value={Math.min(campaign.targetProgress, 100)} className="h-1.5" /><span className="text-xs font-medium text-slate-500">{percent(campaign.targetProgress)}</span></div></button>)}</CardContent></Card>
      <div className="grid gap-5"><Card className="border-0 shadow-sm"><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="text-lg">Prochaines publications</CardTitle><CalendarDays className="h-5 w-5 text-violet-600" /></CardHeader><CardContent className="space-y-3">{data.upcomingContent.slice(0, 3).map(item => <div key={item.id} className="flex items-start gap-3 rounded-xl bg-slate-50 p-3"><div className="rounded-lg bg-violet-50 p-2 text-violet-600"><CalendarDays className="h-4 w-4" /></div><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{formatDate(item.publishDate)} · {labelFor(item.contentType)}</p></div><StatusBadge value={item.status} /></div>)}</CardContent></Card><Card className="border-0 shadow-sm"><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="text-lg">Événements à venir</CardTitle>{canWrite && <Button size="sm" variant="ghost" onClick={() => setEventOpen(true)}><Plus className="mr-1 h-4 w-4" />Ajouter</Button>}</CardHeader><CardContent className="space-y-3">{data.upcomingEvents.slice(0, 2).map(event => <div key={event.id} className="flex items-center gap-3 rounded-xl bg-teal-50/70 p-3"><Video className="h-5 w-5 text-teal-700" /><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{event.title}</p><p className="text-xs text-muted-foreground">{formatDate(event.scheduledAt, true)} · {event.registrationCount} inscrits</p></div></div>)}</CardContent></Card></div></div>
    <CampaignDialog open={campaignOpen} onOpenChange={setCampaignOpen} users={users.data || []} /><LeadDialog open={leadOpen} onOpenChange={setLeadOpen} campaigns={data.campaigns} /><EventDialog open={eventOpen} onOpenChange={setEventOpen} campaigns={data.campaigns} />
  </div>;
}
