import { LeadDialog } from "@/components/crm/MarketingForms";
import { canWriteMarketing, EmptyState, formatDate, labelFor, PageHeader, StatusBadge } from "@/components/crm/Common";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Building2, ExternalLink, Mail, Search, Trash2, UserPlus, UsersRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

export default function MarketingLeads() {
  const [, setLocation] = useLocation(); const [search, setSearch] = useState(""); const [status, setStatus] = useState("Tous"); const [campaignId, setCampaignId] = useState("all"); const [open, setOpen] = useState(false);
  const campaigns = trpc.marketing.campaigns.list.useQuery(); const leads = trpc.marketing.leads.list.useQuery({ search, status, campaignId: campaignId === "all" ? undefined : Number(campaignId) }); const profile = trpc.marketing.profile.useQuery(); const canWrite = canWriteMarketing(profile.data?.role); const utils = trpc.useUtils(); const update = trpc.marketing.leads.update.useMutation(); const promote = trpc.marketing.leads.promote.useMutation(); const remove = trpc.marketing.leads.delete.useMutation();
  const refresh = () => Promise.all([utils.marketing.invalidate(), utils.crm.invalidate(), utils.analytics.invalidate()]);
  const setStatusValue = async (id: number, value: any) => { try { await update.mutateAsync({ id, status: value }); await refresh(); toast.success("Lead mis à jour"); } catch (error) { toast.error(error instanceof Error ? error.message : "Mise à jour impossible"); } };
  const createDeal = async (lead: any) => { try { const result = await promote.mutateAsync({ id: lead.id, amount: 0, assignedTo: null, expectedCloseDate: null }); await refresh(); toast.success(result.existing ? "Opportunité déjà existante" : "Lead transmis au pipeline"); setLocation(`/deals/${result.id}`); } catch (error) { toast.error(error instanceof Error ? error.message : "Transmission impossible"); } };
  const deleteLead = async (id: number) => { if (!confirm("Supprimer ce lead marketing ? La fiche CRM associée sera conservée.")) return; await remove.mutateAsync({ id }); await refresh(); toast.success("Lead supprimé"); };
  return <div className="space-y-6"><PageHeader eyebrow="Marketing & Contenu" title="Leads & qualification" description="Centralisez les demandes issues du site, des campagnes et des événements avant leur transmission au pipeline." actionLabel={canWrite ? "Ajouter un lead" : undefined} onAction={canWrite ? () => setOpen(true) : undefined} />
    <Card className="border-0 shadow-sm"><CardContent className="grid gap-3 p-4 lg:grid-cols-[1fr_220px_260px]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="Nom, e-mail ou organisation…" className="pl-9" /></div><select value={status} onChange={e => setStatus(e.target.value)} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="Tous">Tous les statuts</option>{["Nouveau", "Qualifie", "RDV Planifie", "Converti", "Rejete"].map(value => <option key={value} value={value}>{labelFor(value)}</option>)}</select><select value={campaignId} onChange={e => setCampaignId(e.target.value)} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="all">Toutes les campagnes</option>{campaigns.data?.map(item => <option key={item.id} value={item.id}>{item.name}</option>)}</select></CardContent></Card>
    {leads.data?.length ? <div className="space-y-3">{leads.data.map(lead => <Card key={lead.id} className="border-0 shadow-sm"><CardContent className="flex flex-col gap-4 p-5 xl:flex-row xl:items-center"><div className="flex min-w-0 flex-1 items-start gap-4"><div className="rounded-xl bg-teal-50 p-3 text-teal-700"><UsersRound className="h-5 w-5" /></div><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold text-slate-950">{lead.fullName}</p><StatusBadge value={lead.status} /></div><p className="mt-1 flex items-center gap-1.5 text-sm text-slate-600"><Building2 className="h-3.5 w-3.5" />{lead.organizationName}</p><p className="mt-1 flex items-center gap-1.5 text-xs text-muted-foreground"><Mail className="h-3.5 w-3.5" />{lead.email} · {formatDate(lead.createdAt)} · {lead.campaignName || labelFor(lead.source)}</p></div></div><div className="flex flex-wrap items-center gap-2">{canWrite ? <select value={lead.status} onChange={e => setStatusValue(lead.id, e.target.value)} className="h-9 rounded-lg border border-slate-200 bg-white px-3 text-sm">{["Nouveau", "Qualifie", "RDV Planifie", "Converti", "Rejete"].map(value => <option key={value} value={value}>{labelFor(value)}</option>)}</select> : <StatusBadge value={lead.status} />}{lead.organizationId && <Button size="sm" variant="outline" onClick={() => setLocation(`/organisations/${lead.organizationId}`)}><ExternalLink className="mr-2 h-4 w-4" />CRM</Button>}{canWrite && <Button size="sm" onClick={() => createDeal(lead)} className="bg-[#123653]">{lead.dealId ? "Ouvrir le deal" : "Vers le pipeline"}<ArrowRight className="ml-2 h-4 w-4" /></Button>}{canWrite && <Button size="icon" variant="ghost" className="text-rose-600" onClick={() => deleteLead(lead.id)}><Trash2 className="h-4 w-4" /></Button>}</div></CardContent></Card>)}</div> : <EmptyState icon={UserPlus} title="Aucun lead" description="Les demandes du site et les ajouts manuels apparaîtront ici." actionLabel={canWrite ? "Ajouter un lead" : undefined} onAction={canWrite ? () => setOpen(true) : undefined} />}
    {open && <LeadDialog open={open} onOpenChange={setOpen} campaigns={campaigns.data || []} />}
  </div>;
}
