import { CampaignDialog } from "@/components/crm/MarketingForms";
import { canWriteMarketing, EmptyState, formatCurrency, formatDate, labelFor, PageHeader, StatusBadge } from "@/components/crm/Common";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Progress } from "@/components/ui/progress";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { ArrowRight, Megaphone, Pencil, Plus, Search, Trash2 } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

export default function MarketingCampaigns() {
  const [, setLocation] = useLocation(); const [search, setSearch] = useState(""); const [status, setStatus] = useState("Tous"); const [channel, setChannel] = useState("Tous"); const [editing, setEditing] = useState<any>(null); const [open, setOpen] = useState(false);
  const campaigns = trpc.marketing.campaigns.list.useQuery({ search, status, channel }); const users = trpc.marketing.users.useQuery(); const profile = trpc.marketing.profile.useQuery(); const utils = trpc.useUtils(); const remove = trpc.marketing.campaigns.delete.useMutation(); const canWrite = canWriteMarketing(profile.data?.role);
  const deleteCampaign = async (id: number) => { if (!confirm("Supprimer cette campagne ? Les leads et contenus resteront conservés sans rattachement.")) return; try { await remove.mutateAsync({ id }); await utils.marketing.invalidate(); toast.success("Campagne supprimée"); } catch (error) { toast.error(error instanceof Error ? error.message : "Suppression impossible"); } };
  return <div className="space-y-6"><PageHeader eyebrow="Marketing & Contenu" title="Campagnes" description="Comparez les canaux, les budgets, les objectifs et la transformation jusqu’au client." actionLabel={canWrite ? "Nouvelle campagne" : undefined} onAction={canWrite ? () => { setEditing(null); setOpen(true); } : undefined} />
    <Card className="border-0 shadow-sm"><CardContent className="grid gap-3 p-4 md:grid-cols-[1fr_220px_220px]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="Rechercher une campagne…" className="pl-9" /></div><select value={channel} onChange={e => setChannel(e.target.value)} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="Tous">Tous les canaux</option>{["Email", "Reseaux Sociaux", "SEO-Contenu", "Salon Professionnel", "Webinaire", "Publicite Payante", "Autre"].map(value => <option key={value} value={value}>{labelFor(value)}</option>)}</select><select value={status} onChange={e => setStatus(e.target.value)} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="Tous">Tous les statuts</option>{["Planifiee", "En Cours", "Terminee"].map(value => <option key={value} value={value}>{labelFor(value)}</option>)}</select></CardContent></Card>
    {campaigns.isLoading ? <div className="grid gap-4 lg:grid-cols-2">{Array.from({ length: 4 }, (_, index) => <Skeleton key={index} className="h-64 rounded-2xl" />)}</div> : campaigns.data?.length ? <div className="grid gap-4 xl:grid-cols-2">{campaigns.data.map(item => <Card key={item.id} className="group border-0 shadow-sm transition hover:-translate-y-0.5 hover:shadow-md"><CardContent className="p-5"><div className="flex items-start justify-between gap-4"><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><StatusBadge value={item.status} /><span className="text-xs font-medium text-slate-500">{labelFor(item.channel)}</span></div><h2 className="mt-3 text-xl font-semibold text-slate-950">{item.name}</h2><p className="mt-2 line-clamp-2 text-sm leading-6 text-muted-foreground">{item.objective || "Objectif à préciser"}</p></div>{canWrite && <div className="flex"><Button size="icon" variant="ghost" onClick={() => { setEditing(item); setOpen(true); }}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" className="text-rose-600" onClick={() => deleteCampaign(item.id)}><Trash2 className="h-4 w-4" /></Button></div>}</div><div className="mt-5 grid grid-cols-3 gap-3 border-y border-slate-100 py-4"><Metric label="Budget" value={formatCurrency(item.budget)} /><Metric label="Leads" value={String(item.leadCount)} /><Metric label="CPL" value={item.cpl === null ? "—" : formatCurrency(item.cpl)} /></div><div className="mt-4"><div className="mb-2 flex justify-between text-xs"><span className="text-muted-foreground">Objectif {item.targetLeads} leads</span><strong>{item.targetProgress.toLocaleString("fr-FR", { maximumFractionDigits: 0 })} %</strong></div><Progress value={Math.min(item.targetProgress, 100)} className="h-2" /></div><div className="mt-5 flex flex-wrap items-center justify-between gap-3"><div className="text-xs text-muted-foreground">{formatDate(item.startDate)} → {formatDate(item.endDate)} · ROI {item.roi === null ? "—" : `${item.roi.toLocaleString("fr-FR")} %`}</div><Button variant="ghost" onClick={() => setLocation(`/marketing/campagnes/${item.id}`)} className="text-teal-700">Ouvrir <ArrowRight className="ml-2 h-4 w-4" /></Button></div></CardContent></Card>)}</div> : <EmptyState icon={Megaphone} title="Aucune campagne" description="Créez votre première campagne et reliez-y vos leads et contenus." actionLabel={canWrite ? "Nouvelle campagne" : undefined} onAction={canWrite ? () => setOpen(true) : undefined} />}
    {open && <CampaignDialog key={editing?.id || "new"} open={open} onOpenChange={setOpen} initial={editing} users={users.data || []} />}
  </div>;
}
function Metric({ label, value }: { label: string; value: string }) { return <div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-1 text-lg font-semibold text-slate-900">{value}</p></div>; }
