import { ContentDialog, EventDialog } from "@/components/crm/MarketingForms";
import { canWriteMarketing, EmptyState, formatDate, labelFor, PageHeader, StatusBadge } from "@/components/crm/Common";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { trpc } from "@/lib/trpc";
import { CalendarDays, ExternalLink, FileText, Pencil, Plus, Search, Trash2, Video } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

export default function MarketingCalendar() {
  const [search, setSearch] = useState(""); const [status, setStatus] = useState("Tous"); const [contentOpen, setContentOpen] = useState(false); const [eventOpen, setEventOpen] = useState(false); const [editingContent, setEditingContent] = useState<any>(null); const [editingEvent, setEditingEvent] = useState<any>(null);
  const content = trpc.marketing.content.list.useQuery({ search, status }); const events = trpc.marketing.events.list.useQuery(); const campaigns = trpc.marketing.campaigns.list.useQuery(); const users = trpc.marketing.users.useQuery(); const profile = trpc.marketing.profile.useQuery(); const canWrite = canWriteMarketing(profile.data?.role); const utils = trpc.useUtils(); const deleteContent = trpc.marketing.content.delete.useMutation(); const deleteEvent = trpc.marketing.events.delete.useMutation();
  const months = useMemo(() => { const groups = new Map<string, any[]>(); for (const item of content.data || []) { const key = item.publishDate?.slice(0, 7) || "Sans date"; groups.set(key, [...(groups.get(key) || []), item]); } return Array.from(groups.entries()); }, [content.data]);
  const removeContent = async (id: number) => { if (!confirm("Supprimer ce contenu ?")) return; await deleteContent.mutateAsync({ id }); await utils.marketing.invalidate(); toast.success("Contenu supprimé"); };
  const removeEvent = async (id: number) => { if (!confirm("Supprimer cet événement ?")) return; await deleteEvent.mutateAsync({ id }); await utils.marketing.invalidate(); toast.success("Événement supprimé"); };
  return <div className="space-y-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><PageHeader eyebrow="Marketing & Contenu" title="Calendrier éditorial" description="Orchestrez les contenus et les événements collectifs sans perdre le lien avec leurs campagnes." /><div className="flex gap-2">{canWrite && <><Button variant="outline" className="bg-white" onClick={() => { setEditingEvent(null); setEventOpen(true); }}><Video className="mr-2 h-4 w-4" />Nouvel événement</Button><Button className="bg-[#123653]" onClick={() => { setEditingContent(null); setContentOpen(true); }}><Plus className="mr-2 h-4 w-4" />Nouveau contenu</Button></>}</div></div>
    <Tabs defaultValue="contenus"><TabsList className="bg-white shadow-sm"><TabsTrigger value="contenus">Planning contenus</TabsTrigger><TabsTrigger value="evenements">Webinaires & démos</TabsTrigger></TabsList><TabsContent value="contenus" className="mt-5 space-y-5"><Card className="border-0 shadow-sm"><CardContent className="grid gap-3 p-4 md:grid-cols-[1fr_220px]"><div className="relative"><Search className="absolute left-3 top-3 h-4 w-4 text-slate-400" /><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="Rechercher un contenu…" className="pl-9" /></div><select value={status} onChange={e => setStatus(e.target.value)} className="h-10 rounded-lg border border-slate-200 bg-white px-3 text-sm"><option value="Tous">Tous les statuts</option>{["Idee", "En Redaction", "Planifie", "Publie"].map(value => <option key={value} value={value}>{labelFor(value)}</option>)}</select></CardContent></Card>{months.length ? months.map(([month, items]) => <Card key={month} className="border-0 shadow-sm"><CardHeader><CardTitle className="text-lg">{month === "Sans date" ? month : new Intl.DateTimeFormat("fr-FR", { month: "long", year: "numeric" }).format(new Date(`${month}-01T12:00:00Z`))}</CardTitle></CardHeader><CardContent className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{items.map(item => <article key={item.id} className="rounded-xl border border-slate-100 bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><div className="rounded-lg bg-white p-2 text-violet-600 shadow-sm"><FileText className="h-4 w-4" /></div><StatusBadge value={item.status} /></div><h3 className="mt-4 font-semibold text-slate-900">{item.title}</h3><p className="mt-1 text-xs text-muted-foreground">{formatDate(item.publishDate)} · {labelFor(item.contentType)}</p><p className="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">{item.brief || "Brief à compléter"}</p><div className="mt-4 flex items-center justify-between border-t border-slate-200 pt-3"><span className="truncate text-xs text-muted-foreground">{item.campaignName || "Hors campagne"}</span><div className="flex">{item.publicationUrl && <Button size="icon" variant="ghost" asChild><a href={item.publicationUrl} target="_blank" rel="noreferrer"><ExternalLink className="h-4 w-4" /></a></Button>}{canWrite && <><Button size="icon" variant="ghost" onClick={() => { setEditingContent(item); setContentOpen(true); }}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" className="text-rose-600" onClick={() => removeContent(item.id)}><Trash2 className="h-4 w-4" /></Button></>}</div></div></article>)}</CardContent></Card>) : <EmptyState icon={CalendarDays} title="Aucun contenu planifié" description="Ajoutez un contenu à votre calendrier éditorial." />}</TabsContent>
      <TabsContent value="evenements" className="mt-5"><div className="grid gap-4 xl:grid-cols-2">{events.data?.map(event => <Card key={event.id} className="border-0 shadow-sm"><CardContent className="p-5"><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><div className="rounded-xl bg-teal-50 p-3 text-teal-700"><Video className="h-5 w-5" /></div><div><p className="font-semibold">{event.title}</p><p className="mt-1 text-xs text-muted-foreground">{labelFor(event.eventType)} · {formatDate(event.scheduledAt, true)}</p></div></div><StatusBadge value={event.status} /></div><div className="mt-5 grid grid-cols-3 gap-3"><EventMetric label="Inscrits" value={event.registrationCount} /><EventMetric label="Présents" value={event.attendeeCount} /><EventMetric label="RDV" value={event.meetingsBooked} /></div><div className="mt-4 flex items-center justify-between"><span className="text-xs text-muted-foreground">{event.campaignName || "Hors campagne"}</span>{canWrite && <div><Button size="icon" variant="ghost" onClick={() => { setEditingEvent(event); setEventOpen(true); }}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" className="text-rose-600" onClick={() => removeEvent(event.id)}><Trash2 className="h-4 w-4" /></Button></div>}</div></CardContent></Card>)}</div></TabsContent></Tabs>
    {contentOpen && <ContentDialog key={editingContent?.id || "new"} open={contentOpen} onOpenChange={setContentOpen} initial={editingContent} campaigns={campaigns.data || []} users={users.data || []} />}{eventOpen && <EventDialog key={editingEvent?.id || "new"} open={eventOpen} onOpenChange={setEventOpen} initial={editingEvent} campaigns={campaigns.data || []} />}
  </div>;
}
function EventMetric({ label, value }: { label: string; value: number }) { return <div className="rounded-xl bg-slate-50 p-3 text-center"><p className="text-xl font-semibold">{value}</p><p className="text-xs text-muted-foreground">{label}</p></div>; }
