import { AssetDialog, CampaignDialog, ContentDialog, EventDialog } from "@/components/crm/MarketingForms";
import { canWriteMarketing, EmptyState, formatCurrency, formatDate, labelFor, PageHeader, StatCard, StatusBadge } from "@/components/crm/Common";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { trpc } from "@/lib/trpc";
import { BookOpen, CalendarDays, CircleDollarSign, Download, ExternalLink, FileText, Megaphone, Pencil, Plus, Target, Trash2, UserRoundCheck, UsersRound, Video } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

export default function MarketingCampaignDetail({ id }: { id: number }) {
  const [, setLocation] = useLocation(); const query = trpc.marketing.campaigns.get.useQuery({ id }); const users = trpc.marketing.users.useQuery(); const profile = trpc.marketing.profile.useQuery(); const utils = trpc.useUtils();
  const [campaignOpen, setCampaignOpen] = useState(false); const [contentOpen, setContentOpen] = useState(false); const [eventOpen, setEventOpen] = useState(false); const [assetOpen, setAssetOpen] = useState(false);
  const updateLead = trpc.marketing.leads.update.useMutation(); const promote = trpc.marketing.leads.promote.useMutation(); const removeAsset = trpc.marketing.assets.delete.useMutation(); const canWrite = canWriteMarketing(profile.data?.role); const data = query.data;
  const refresh = () => Promise.all([utils.marketing.invalidate(), utils.crm.invalidate(), utils.analytics.invalidate()]);
  const setLeadStatus = async (leadId: number, status: "Nouveau" | "Qualifie" | "RDV Planifie" | "Converti" | "Rejete") => { try { await updateLead.mutateAsync({ id: leadId, status }); await refresh(); toast.success("Statut du lead mis à jour"); } catch (error) { toast.error(error instanceof Error ? error.message : "Mise à jour impossible"); } };
  const createDeal = async (leadId: number) => { try { const result = await promote.mutateAsync({ id: leadId, amount: 0, assignedTo: null, expectedCloseDate: null }); await refresh(); toast.success(result.existing ? "Opportunité déjà existante" : "Opportunité créée dans le CRM"); setLocation(`/deals/${result.id}`); } catch (error) { toast.error(error instanceof Error ? error.message : "Création impossible"); } };
  if (query.isLoading) return <div className="p-8 text-center text-sm text-muted-foreground">Chargement de la campagne…</div>;
  if (!data) return <EmptyState icon={Megaphone} title="Campagne introuvable" description="Cette campagne n’existe plus ou vous n’y avez pas accès." />;
  const campaign = data.campaign;
  return <div className="space-y-6"><div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><PageHeader backTo="/marketing/campagnes" eyebrow={labelFor(campaign.channel)} title={campaign.name} description={campaign.objective || "Objectif à préciser"} /><div className="flex flex-wrap gap-2">{canWrite && <><Button variant="outline" onClick={() => setCampaignOpen(true)} className="bg-white"><Pencil className="mr-2 h-4 w-4" />Modifier</Button><Button onClick={() => setContentOpen(true)} className="bg-[#123653]"><Plus className="mr-2 h-4 w-4" />Planifier un contenu</Button></>}</div></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><StatCard label="Leads capturés" value={String(campaign.leadCount)} detail={`${campaign.qualifiedLeads} qualifiés`} icon={UsersRound} accent="teal" /><StatCard label="Coût par lead" value={campaign.cpl === null ? "—" : formatCurrency(campaign.cpl)} detail={`Budget ${formatCurrency(campaign.budget)}`} icon={Target} accent="amber" /><StatCard label="Conversion client" value={`${campaign.conversionRate.toLocaleString("fr-FR")} %`} detail={`${campaign.convertedLeads} leads convertis`} icon={UserRoundCheck} accent="violet" /><StatCard label="ROI attribué" value={campaign.roi === null ? "—" : `${campaign.roi.toLocaleString("fr-FR")} %`} detail={`${formatCurrency(campaign.attributedRevenue)} attribués`} icon={CircleDollarSign} accent="navy" /></div>
    <Card className="border-0 shadow-sm"><CardContent className="grid gap-5 p-5 md:grid-cols-[1fr_auto]"><div><div className="mb-2 flex items-center justify-between text-sm"><span>Progression vers l’objectif de {campaign.targetLeads} leads</span><strong>{campaign.targetProgress.toLocaleString("fr-FR", { maximumFractionDigits: 0 })} %</strong></div><Progress value={Math.min(campaign.targetProgress, 100)} className="h-2.5" /></div><div className="flex items-center gap-3 text-sm"><StatusBadge value={campaign.status} /><span className="text-muted-foreground">{formatDate(campaign.startDate)} → {formatDate(campaign.endDate)}</span></div></CardContent></Card>
    <Tabs defaultValue="leads"><TabsList className="h-auto flex-wrap justify-start bg-white p-1 shadow-sm"><TabsTrigger value="leads">Leads ({data.leads.length})</TabsTrigger><TabsTrigger value="contenus">Contenus ({data.content.length})</TabsTrigger><TabsTrigger value="evenements">Événements ({data.events.length})</TabsTrigger><TabsTrigger value="supports">Supports ({data.assets.length})</TabsTrigger><TabsTrigger value="pipeline">Pipeline ({data.deals.length})</TabsTrigger></TabsList>
      <TabsContent value="leads" className="mt-5"><Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-lg">Leads de la campagne</CardTitle></CardHeader><CardContent className="space-y-3">{data.leads.length ? data.leads.map(lead => <div key={lead.id} className="flex flex-col gap-3 rounded-xl border border-slate-100 bg-slate-50 p-4 lg:flex-row lg:items-center"><div className="min-w-0 flex-1"><p className="font-semibold">{lead.fullName}</p><p className="mt-1 text-xs text-muted-foreground">{lead.organizationName} · {lead.email} · {formatDate(lead.createdAt)}</p></div><div className="flex flex-wrap items-center gap-2">{canWrite ? <select value={lead.status} onChange={e => setLeadStatus(lead.id, e.target.value as any)} className="h-9 rounded-lg border border-slate-200 bg-white px-3 text-sm">{["Nouveau", "Qualifie", "RDV Planifie", "Converti", "Rejete"].map(value => <option key={value} value={value}>{labelFor(value)}</option>)}</select> : <StatusBadge value={lead.status} />}{canWrite && <Button size="sm" variant="outline" onClick={() => createDeal(lead.id)}>{lead.dealId ? "Ouvrir l’opportunité" : "Créer une opportunité"}</Button>}</div></div>) : <EmptyState icon={UsersRound} title="Aucun lead" description="Les leads rattachés à la campagne apparaîtront ici." />}</CardContent></Card></TabsContent>
      <TabsContent value="contenus" className="mt-5"><Section title="Planning éditorial" action={canWrite ? () => setContentOpen(true) : undefined} actionLabel="Ajouter"><div className="grid gap-3 md:grid-cols-2">{data.content.map(item => <div key={item.id} className="rounded-xl bg-slate-50 p-4"><div className="flex justify-between gap-3"><div><p className="font-semibold">{item.title}</p><p className="mt-1 text-xs text-muted-foreground">{labelFor(item.contentType)} · {formatDate(item.publishDate)}</p></div><StatusBadge value={item.status} /></div><p className="mt-3 line-clamp-2 text-sm text-slate-600">{item.brief || "Brief à compléter"}</p></div>)}</div></Section></TabsContent>
      <TabsContent value="evenements" className="mt-5"><Section title="Webinaires & démonstrations" action={canWrite ? () => setEventOpen(true) : undefined} actionLabel="Ajouter"><div className="grid gap-3 md:grid-cols-2">{data.events.map(event => <div key={event.id} className="rounded-xl bg-slate-50 p-4"><div className="flex items-start justify-between"><div><p className="font-semibold">{event.title}</p><p className="mt-1 text-xs text-muted-foreground">{labelFor(event.eventType)} · {formatDate(event.scheduledAt, true)}</p></div><StatusBadge value={event.status} /></div><div className="mt-4 grid grid-cols-3 gap-2 text-center text-xs"><Mini label="Inscrits" value={event.registrationCount} /><Mini label="Présents" value={event.attendeeCount} /><Mini label="RDV" value={event.meetingsBooked} /></div></div>)}</div></Section></TabsContent>
      <TabsContent value="supports" className="mt-5"><Section title="Supports de campagne" action={canWrite ? () => setAssetOpen(true) : undefined} actionLabel="Importer"><div className="grid gap-3 md:grid-cols-2">{data.assets.map(asset => <div key={asset.id} className="flex items-center gap-3 rounded-xl bg-slate-50 p-4"><div className="rounded-xl bg-white p-3 text-teal-700 shadow-sm"><FileText className="h-5 w-5" /></div><div className="min-w-0 flex-1"><p className="truncate font-semibold">{asset.title}</p><p className="mt-1 text-xs text-muted-foreground">{labelFor(asset.assetType)} · {formatFileSize(asset.sizeBytes)}</p></div><Button size="icon" variant="ghost" asChild><a href={asset.fileUrl} target="_blank" rel="noreferrer"><Download className="h-4 w-4" /></a></Button>{canWrite && <Button size="icon" variant="ghost" className="text-rose-600" onClick={async () => { await removeAsset.mutateAsync({ id: asset.id }); await refresh(); }}><Trash2 className="h-4 w-4" /></Button>}</div>)}</div></Section></TabsContent>
      <TabsContent value="pipeline" className="mt-5"><Section title="Opportunités attribuées"><div className="space-y-3">{data.deals.map(deal => <button key={deal.id} onClick={() => setLocation(`/deals/${deal.id}`)} className="flex w-full items-center gap-4 rounded-xl bg-slate-50 p-4 text-left hover:bg-slate-100"><Megaphone className="h-5 w-5 text-teal-600" /><div className="min-w-0 flex-1"><p className="font-semibold">{deal.title}</p><p className="text-xs text-muted-foreground">{deal.organizationName}</p></div><StatusBadge value={deal.stage} /><strong>{formatCurrency(deal.amount)}</strong><ExternalLink className="h-4 w-4 text-slate-400" /></button>)}</div></Section></TabsContent>
    </Tabs>
    {campaignOpen && <CampaignDialog open={campaignOpen} onOpenChange={setCampaignOpen} initial={campaign} users={users.data || []} />}{contentOpen && <ContentDialog open={contentOpen} onOpenChange={setContentOpen} campaigns={[campaign]} users={users.data || []} />}{eventOpen && <EventDialog open={eventOpen} onOpenChange={setEventOpen} campaigns={[campaign]} />}{assetOpen && <AssetDialog open={assetOpen} onOpenChange={setAssetOpen} campaigns={[campaign]} />}
  </div>;
}
function Section({ title, action, actionLabel, children }: { title: string; action?: () => void; actionLabel?: string; children: React.ReactNode }) { return <Card className="border-0 shadow-sm"><CardHeader className="flex flex-row items-center justify-between"><CardTitle className="text-lg">{title}</CardTitle>{action && <Button size="sm" variant="outline" onClick={action}><Plus className="mr-1 h-4 w-4" />{actionLabel}</Button>}</CardHeader><CardContent>{children}</CardContent></Card>; }
function Mini({ label, value }: { label: string; value: number }) { return <div className="rounded-lg bg-white p-2"><strong className="block text-base">{value}</strong><span className="text-muted-foreground">{label}</span></div>; }
function formatFileSize(bytes: number) { return bytes < 1024 ? `${bytes} o` : `${(bytes / 1024).toLocaleString("fr-FR", { maximumFractionDigits: 1 })} Ko`; }
