import { canWriteCrm, EmptyState, formatCurrency, formatDate, labelFor, PageHeader, StatusBadge } from "@/components/crm/Common";
import { ContactDialog, DealDialog, DeleteDialog, OrganizationDialog } from "@/components/crm/Forms";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { trpc } from "@/lib/trpc";
import { BriefcaseBusiness, Building2, Mail, MapPin, Pencil, Phone, Plus, Trash2, UserRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

export default function OrganizationDetail({ id }: { id: number }) {
  const [, setLocation] = useLocation(); const utils = trpc.useUtils(); const query = trpc.crm.organizations.get.useQuery({ id }); const profile = trpc.crm.profile.useQuery(); const remove = trpc.crm.organizations.delete.useMutation(); const canWrite = canWriteCrm(profile.data?.role); const [dialog, setDialog] = useState<"edit" | "delete" | "contact" | "deal" | null>(null);
  if (query.isLoading) return <div className="mx-auto max-w-[1400px] space-y-5"><Skeleton className="h-24" /><Skeleton className="h-72" /></div>;
  if (!query.data) return <EmptyState icon={Building2} title="Organisation introuvable" description="Cette organisation n’existe plus ou n’est pas accessible." />;
  const { organization, contacts, deals } = query.data;
  const confirmDelete = async () => { try { await remove.mutateAsync({ id }); await Promise.all([utils.crm.organizations.invalidate(), utils.crm.deals.invalidate()]); toast.success("Organisation supprimée"); setLocation("/organisations"); } catch (error) { toast.error(error instanceof Error ? error.message : "Suppression impossible"); } };
  return <div className="reveal mx-auto max-w-[1400px]"><PageHeader backTo="/organisations" eyebrow={labelFor(organization.type)} title={organization.name} description={`${organization.city || "Localisation non renseignée"} · Source : ${labelFor(organization.leadSource)}`} />
    <div className="mb-5 flex flex-wrap items-center gap-2"><StatusBadge value={organization.status} />{canWrite ? <><Button variant="outline" size="sm" className="bg-white" onClick={() => setDialog("edit")}><Pencil className="mr-2 h-4 w-4" />Modifier</Button><Button variant="ghost" size="sm" className="text-rose-600" onClick={() => setDialog("delete")}><Trash2 className="mr-2 h-4 w-4" />Supprimer</Button></> : null}</div>
    <div className="grid gap-5 lg:grid-cols-[.7fr_1.3fr]">
      <Card className="soft-card"><CardHeader><CardTitle className="text-base">Informations</CardTitle></CardHeader><CardContent className="space-y-5"><Info icon={MapPin} label="Adresse" value={[organization.address, organization.postalCode, organization.city].filter(Boolean).join(", ") || "Non renseignée"} /><Info icon={BriefcaseBusiness} label="Valeur annuelle" value={formatCurrency(organization.annualContractValue)} /><Info icon={UserRound} label="Contacts" value={`${contacts.length} contact${contacts.length > 1 ? "s" : ""}`} /><div className="grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-4"><div><p className="text-xs text-muted-foreground">Créée le</p><p className="mt-1 text-sm font-semibold">{formatDate(organization.createdAt)}</p></div><div><p className="text-xs text-muted-foreground">Onboarding</p><p className="mt-1 text-sm font-semibold">{labelFor(organization.onboardingStatus)}</p></div></div></CardContent></Card>
      <div className="space-y-5"><Card className="soft-card"><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle className="text-base">Contacts</CardTitle><p className="mt-1 text-xs text-muted-foreground">Interlocuteurs de l’établissement</p></div>{canWrite ? <Button size="sm" variant="outline" className="bg-white" onClick={() => setDialog("contact")}><Plus className="mr-1 h-4 w-4" />Ajouter</Button> : null}</CardHeader><CardContent>{contacts.length ? <div className="grid gap-3 sm:grid-cols-2">{contacts.map(contact => <button key={contact.id} onClick={() => setLocation(`/contacts/${contact.id}`)} className="flex items-center gap-3 rounded-xl border border-slate-100 p-3 text-left hover:bg-slate-50"><Avatar className="h-9 w-9"><AvatarFallback className="bg-teal-50 text-xs font-bold text-teal-700">{contact.fullName.split(" ").map(part => part[0]).slice(-2).join("")}</AvatarFallback></Avatar><div className="min-w-0"><p className="truncate text-sm font-semibold">{contact.fullName}</p><p className="truncate text-xs text-muted-foreground">{contact.jobTitle || contact.specialty || contact.email}</p></div></button>)}</div> : <p className="py-6 text-center text-sm text-muted-foreground">Aucun contact associé.</p>}</CardContent></Card>
        <Card className="soft-card"><CardHeader className="flex flex-row items-center justify-between"><div><CardTitle className="text-base">Opportunités</CardTitle><p className="mt-1 text-xs text-muted-foreground">Historique et pipeline actif</p></div>{canWrite ? <Button size="sm" variant="outline" className="bg-white" onClick={() => setDialog("deal")}><Plus className="mr-1 h-4 w-4" />Ajouter</Button> : null}</CardHeader><CardContent>{deals.length ? <div className="space-y-2">{deals.map(deal => <button key={deal.id} onClick={() => setLocation(`/deals/${deal.id}`)} className="flex w-full items-center gap-3 rounded-xl border border-slate-100 p-3 text-left hover:bg-slate-50"><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{deal.title}</p><p className="text-xs text-muted-foreground">{deal.ownerName || "Non assigné"} · clôture {formatDate(deal.expectedCloseDate)}</p></div><StatusBadge value={deal.stage} /><p className="hidden text-sm font-semibold sm:block">{formatCurrency(deal.amount)}</p></button>)}</div> : <p className="py-6 text-center text-sm text-muted-foreground">Aucune opportunité associée.</p>}</CardContent></Card></div>
    </div>
    {dialog === "edit" ? <OrganizationDialog open onOpenChange={() => setDialog(null)} initial={organization} /> : null}{dialog === "contact" ? <ContactDialog open onOpenChange={() => setDialog(null)} defaultOrganizationId={id} /> : null}{dialog === "deal" ? <DealDialog open onOpenChange={() => setDialog(null)} defaultOrganizationId={id} /> : null}{dialog === "delete" ? <DeleteDialog open onOpenChange={() => setDialog(null)} title="Supprimer cette organisation ?" description="Ses opportunités seront supprimées et ses contacts dissociés." onConfirm={confirmDelete} pending={remove.isPending} /> : null}
  </div>;
}

function Info({ icon: Icon, label, value }: { icon: any; label: string; value: string }) { return <div className="flex gap-3"><div className="mt-0.5 flex h-8 w-8 shrink-0 items-center justify-center rounded-lg bg-slate-100 text-slate-500"><Icon className="h-4 w-4" /></div><div><p className="text-xs font-medium text-muted-foreground">{label}</p><p className="mt-0.5 text-sm font-semibold leading-5 text-slate-900">{value}</p></div></div>; }
