import { canWriteCrm, EmptyState, formatCurrency, formatDate, labelFor, PageHeader, StatusBadge, STAGES } from "@/components/crm/Common";
import { DealDialog, DeleteDialog } from "@/components/crm/Forms";
import { Avatar, AvatarFallback } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";
import { Input } from "@/components/ui/input";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { trpc } from "@/lib/trpc";
import { Building2, CalendarDays, ChevronRight, Columns3, GripVertical, List, Pencil, Search, Trash2 } from "lucide-react";
import { DragEvent, useState } from "react";
import { toast } from "sonner";
import { useLocation } from "wouter";

export default function PipelinePage() {
  const [, setLocation] = useLocation(); const utils = trpc.useUtils(); const [search, setSearch] = useState(""); const [dialog, setDialog] = useState<{ type: "create" | "edit" | "delete"; item?: any } | null>(null); const [dragged, setDragged] = useState<number | null>(null);
  const profile = trpc.crm.profile.useQuery(); const query = trpc.crm.deals.list.useQuery({ search }); const move = trpc.crm.deals.move.useMutation(); const remove = trpc.crm.deals.delete.useMutation(); const canWrite = canWriteCrm(profile.data?.role);
  const moveDeal = async (id: number, stage: typeof STAGES[number]) => { const previous = query.data; utils.crm.deals.list.setData({ search }, old => old?.map(deal => deal.id === id ? { ...deal, stage } : deal)); try { await move.mutateAsync({ id, stage }); await Promise.all([utils.crm.deals.invalidate(), utils.crm.dashboard.invalidate(), utils.crm.organizations.invalidate()]); toast.success(`Opportunité déplacée vers « ${labelFor(stage)} »`); } catch (error) { utils.crm.deals.list.setData({ search }, previous); toast.error(error instanceof Error ? error.message : "Déplacement impossible"); } setDragged(null); };
  const onDrop = (event: DragEvent, stage: typeof STAGES[number]) => { event.preventDefault(); const id = Number(event.dataTransfer.getData("text/deal-id") || dragged); if (id && canWrite) void moveDeal(id, stage); };
  const confirmDelete = async () => { if (!dialog?.item) return; try { await remove.mutateAsync({ id: dialog.item.id }); await Promise.all([utils.crm.deals.invalidate(), utils.crm.dashboard.invalidate()]); toast.success("Opportunité supprimée"); setDialog(null); } catch (error) { toast.error(error instanceof Error ? error.message : "Suppression impossible"); } };
  const data = query.data || [];
  return <div className="reveal mx-auto max-w-[1700px]"><PageHeader eyebrow="Cycle de vente" title="Pipeline commercial" description="Faites progresser chaque opportunité de la prospection à la signature." actionLabel={canWrite ? "Nouvelle opportunité" : undefined} onAction={() => setDialog({ type: "create" })} />
    <Tabs defaultValue="kanban"><div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div className="relative min-w-0 flex-1 sm:max-w-md"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><Input value={search} onChange={e => setSearch(e.target.value)} placeholder="Rechercher une opportunité…" className="h-10 border-slate-200 bg-white pl-9" /></div><TabsList className="grid w-full grid-cols-2 bg-slate-200/60 sm:w-56"><TabsTrigger value="kanban"><Columns3 className="mr-2 h-4 w-4" />Kanban</TabsTrigger><TabsTrigger value="liste"><List className="mr-2 h-4 w-4" />Liste</TabsTrigger></TabsList></div>
      <TabsContent value="kanban" className="mt-0"><div className="overflow-x-auto pb-4"><div className="grid min-w-[1600px] grid-cols-6 gap-3">{STAGES.map(stage => { const deals = data.filter(deal => deal.stage === stage); const total = deals.reduce((sum, deal) => sum + Number(deal.amount), 0); return <div key={stage} onDragOver={event => canWrite && event.preventDefault()} onDrop={event => onDrop(event, stage)} className={`min-h-[560px] rounded-2xl border border-slate-200/80 bg-slate-100/65 p-3 transition-colors ${dragged ? "hover:border-teal-400 hover:bg-teal-50/50" : ""}`}><div className="mb-3 flex items-start justify-between px-1"><div><div className="flex items-center gap-2"><StatusBadge value={stage} /><span className="rounded-full bg-white px-2 py-0.5 text-xs font-semibold text-slate-600">{deals.length}</span></div><p className="mt-2 text-xs font-semibold text-slate-500">{formatCurrency(total)}</p></div></div><div className="space-y-3">{deals.map(deal => <Card key={deal.id} draggable={canWrite} onDragStart={event => { setDragged(deal.id); event.dataTransfer.setData("text/deal-id", String(deal.id)); }} onDragEnd={() => setDragged(null)} className={`group cursor-pointer border-0 bg-white p-4 shadow-[0_1px_2px_rgba(15,23,42,.06),0_6px_16px_rgba(15,23,42,.04)] transition-all hover:-translate-y-0.5 hover:shadow-md ${dragged === deal.id ? "opacity-50" : ""}`} onClick={() => setLocation(`/deals/${deal.id}`)}><div className="mb-3 flex items-start justify-between gap-2"><p className="line-clamp-2 text-sm font-semibold leading-5 text-slate-900">{deal.title}</p>{canWrite ? <GripVertical className="h-4 w-4 shrink-0 text-slate-300" /> : null}</div><p className="mb-4 flex items-center gap-1.5 truncate text-xs text-muted-foreground"><Building2 className="h-3.5 w-3.5" />{deal.organizationName}</p><p className="text-lg font-semibold tracking-tight text-[#123653]">{formatCurrency(deal.amount)}</p><div className="mt-4 flex items-center justify-between border-t border-slate-100 pt-3"><div className="flex items-center gap-2"><Avatar className="h-6 w-6"><AvatarFallback className="bg-slate-100 text-[9px] font-bold">{(deal.ownerName || "NA").split(" ").map(part => part[0]).slice(-2).join("")}</AvatarFallback></Avatar><span className="max-w-24 truncate text-[11px] text-muted-foreground">{deal.ownerName || "Non assigné"}</span></div><span className="flex items-center gap-1 text-[11px] text-muted-foreground"><CalendarDays className="h-3 w-3" />{formatDate(deal.expectedCloseDate)}</span></div></Card>)}</div></div>; })}</div></div></TabsContent>
      <TabsContent value="liste" className="mt-0"><Card className="soft-card overflow-hidden">{data.length ? <div className="divide-y divide-slate-100">{data.map(deal => <div key={deal.id} className="group flex items-center gap-3 p-4 hover:bg-slate-50/70"><button className="flex min-w-0 flex-1 items-center gap-4 text-left" onClick={() => setLocation(`/deals/${deal.id}`)}><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold text-slate-950">{deal.title}</p><p className="mt-1 truncate text-xs text-muted-foreground">{deal.organizationName} · {deal.ownerName || "Non assigné"}</p></div><StatusBadge value={deal.stage} /><p className="hidden min-w-24 text-right text-sm font-semibold sm:block">{formatCurrency(deal.amount)}</p><p className="hidden min-w-24 text-right text-xs text-muted-foreground lg:block">{formatDate(deal.expectedCloseDate)}</p></button>{canWrite ? <div className="flex opacity-100 sm:opacity-0 sm:group-hover:opacity-100"><Button size="icon" variant="ghost" onClick={() => setDialog({ type: "edit", item: deal })}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" className="text-rose-600" onClick={() => setDialog({ type: "delete", item: deal })}><Trash2 className="h-4 w-4" /></Button></div> : null}<ChevronRight className="h-4 w-4 text-slate-300" /></div>)}</div> : <div className="p-4"><EmptyState icon={Columns3} title="Pipeline vide" description="Créez votre première opportunité commerciale." actionLabel={canWrite ? "Nouvelle opportunité" : undefined} onAction={() => setDialog({ type: "create" })} /></div>}</Card></TabsContent>
    </Tabs>
    {dialog?.type === "create" ? <DealDialog open onOpenChange={() => setDialog(null)} /> : null}{dialog?.type === "edit" ? <DealDialog key={dialog.item.id} open onOpenChange={() => setDialog(null)} initial={dialog.item} /> : null}{dialog?.type === "delete" ? <DeleteDialog open onOpenChange={() => setDialog(null)} title="Supprimer cette opportunité ?" description="Les interactions, devis et relances liés seront également supprimés." onConfirm={confirmDelete} pending={remove.isPending} /> : null}
  </div>;
}
