import { canWriteSupport, EmptyState, formatDate, labelFor, PageHeader, StatusBadge } from "@/components/crm/Common";
import { DeleteDialog } from "@/components/crm/Forms";
import { CalendarEventDialog } from "@/components/crm/SupportForms";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { CalendarDays, Clock3, Loader2, MapPin, Pencil, Trash2, Users } from "lucide-react";
import { useMemo, useState } from "react";
import { toast } from "sonner";

export default function SupportCalendar() {
  const utils = trpc.useUtils(); const profile = trpc.support.profile.useQuery(); const query = trpc.support.events.list.useQuery(); const remove = trpc.support.events.delete.useMutation(); const [type, setType] = useState("Tous"); const [dialog, setDialog] = useState<{ open: boolean; item?: any }>({ open: false }); const [deleting, setDeleting] = useState<any>(null); const canWrite = canWriteSupport(profile.data?.role);
  const groups = useMemo(() => { const rows = (query.data || []).filter(event => type === "Tous" || event.eventType === type); return rows.reduce<Record<string, typeof rows>>((acc, event) => { const key = event.startAt.toISOString().slice(0, 10); (acc[key] ||= []).push(event); return acc; }, {}); }, [query.data, type]);
  const confirmDelete = async () => { if (!deleting) return; await remove.mutateAsync({ id: deleting.id }); await Promise.all([query.refetch(), utils.support.dashboard.invalidate()]); setDeleting(null); toast.success("Événement supprimé"); };
  return <div><PageHeader eyebrow="Secrétariat & Support" title="Agenda partagé" description="Coordonnez les rendez-vous internes, démos, échanges clients et échéances." actionLabel={canWrite ? "Nouvel événement" : undefined} onAction={() => setDialog({ open: true })} />
    <div className="mb-5 flex flex-wrap gap-2">{["Tous", "Rendez-vous Interne", "Demo", "Rendez-vous Client", "Echeance", "Autre"].map(value => <Button key={value} size="sm" variant={type === value ? "default" : "outline"} onClick={() => setType(value)} className={type === value ? "bg-[#123653]" : "bg-white"}>{labelFor(value)}</Button>)}</div>
    {query.isLoading ? <div className="flex min-h-64 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin" /></div> : Object.keys(groups).length ? <div className="space-y-6">{Object.entries(groups).map(([date, events]) => <section key={date}><div className="mb-3 flex items-center gap-3"><div className="flex h-11 w-11 flex-col items-center justify-center rounded-xl bg-[#123653] text-white"><span className="text-[10px] font-bold uppercase">{new Intl.DateTimeFormat("fr-FR", { month: "short" }).format(new Date(`${date}T12:00:00`))}</span><span className="text-lg font-semibold leading-none">{new Date(`${date}T12:00:00`).getDate()}</span></div><div><p className="font-semibold capitalize">{new Intl.DateTimeFormat("fr-FR", { weekday: "long", day: "numeric", month: "long" }).format(new Date(`${date}T12:00:00`))}</p><p className="text-xs text-muted-foreground">{events.length} événement{events.length > 1 ? "s" : ""}</p></div></div><div className="ml-5 space-y-3 border-l border-slate-200 pl-8">{events.map(event => <Card key={event.id} className="relative border-0 shadow-sm before:absolute before:-left-[37px] before:top-6 before:h-4 before:w-4 before:rounded-full before:border-4 before:border-[#f6f8fa] before:bg-teal-500"><CardContent className="flex flex-col gap-4 p-4 sm:flex-row sm:items-center"><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><p className="font-semibold">{event.title}</p><StatusBadge value={event.eventType} /></div><div className="mt-2 flex flex-wrap gap-x-5 gap-y-1 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1"><Clock3 className="h-3.5 w-3.5" />{event.allDay ? "Toute la journée" : `${formatDate(event.startAt, true)}${event.endAt ? ` – ${new Intl.DateTimeFormat("fr-FR", { hour: "2-digit", minute: "2-digit" }).format(event.endAt)}` : ""}`}</span>{event.location && <span className="inline-flex items-center gap-1"><MapPin className="h-3.5 w-3.5" />{event.location}</span>}{(event.organizationName || event.organizerName) && <span className="inline-flex items-center gap-1"><Users className="h-3.5 w-3.5" />{event.organizationName || event.organizerName}</span>}</div>{event.description && <p className="mt-3 text-sm text-slate-600">{event.description}</p>}</div>{canWrite && <div className="flex"><Button size="icon" variant="ghost" onClick={() => setDialog({ open: true, item: event })}><Pencil className="h-4 w-4" /></Button><Button size="icon" variant="ghost" className="text-rose-600" onClick={() => setDeleting(event)}><Trash2 className="h-4 w-4" /></Button></div>}</CardContent></Card>)}</div></section>)}</div> : <EmptyState icon={CalendarDays} title="Agenda vide" description="Ajoutez les prochains rendez-vous et échéances partagés." actionLabel={canWrite ? "Nouvel événement" : undefined} onAction={() => setDialog({ open: true })} />}
    {dialog.open && <CalendarEventDialog key={dialog.item?.id || "new"} open={dialog.open} onOpenChange={open => setDialog({ open })} initial={dialog.item} />}
    <DeleteDialog open={!!deleting} onOpenChange={open => !open && setDeleting(null)} title="Supprimer cet événement ?" description="Il disparaîtra de l’agenda partagé." onConfirm={confirmDelete} pending={remove.isPending} />
  </div>;
}
