import { canWriteSupport, formatDate, labelFor, PageHeader, StatusBadge } from "@/components/crm/Common";
import { TicketDialog, TicketEventDialog } from "@/components/crm/SupportForms";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { trpc } from "@/lib/trpc";
import { Building2, CheckCircle2, Clock3, Headphones, Loader2, MessageSquarePlus, Pencil, UserRound } from "lucide-react";
import { useState } from "react";
import { toast } from "sonner";

export default function SupportTicketDetail({ id }: { id: number }) {
  const utils = trpc.useUtils(); const query = trpc.support.tickets.get.useQuery({ id }); const profile = trpc.support.profile.useQuery(); const update = trpc.support.tickets.update.useMutation(); const [editOpen, setEditOpen] = useState(false); const [eventOpen, setEventOpen] = useState(false); const canWrite = canWriteSupport(profile.data?.role);
  if (query.isLoading) return <div className="flex min-h-64 items-center justify-center"><Loader2 className="h-6 w-6 animate-spin" /></div>;
  if (!query.data) return <div className="rounded-2xl bg-white p-8 text-center">Ticket introuvable.</div>;
  const { ticket, events } = query.data;
  const changeStatus = async (status: "Nouveau" | "En cours" | "En attente client" | "Resolu") => { try { await update.mutateAsync({ id, status }); await Promise.all([query.refetch(), utils.support.dashboard.invalidate(), utils.support.tickets.list.invalidate()]); toast.success(status === "Resolu" ? "Ticket résolu" : "Statut mis à jour"); } catch (error) { toast.error(error instanceof Error ? error.message : "Mise à jour impossible"); } };
  return <div>
    <PageHeader backTo="/support/tickets" eyebrow={`Ticket #${ticket.id}`} title={ticket.title} description={`${ticket.organizationName || "Demande interne"}${ticket.contactName ? ` · ${ticket.contactName}` : ""}`} />
    <div className="mb-6 flex flex-wrap items-center gap-2"><StatusBadge value={ticket.priority} /><StatusBadge value={ticket.category} /><StatusBadge value={ticket.status} />{canWrite && <><Button variant="outline" onClick={() => setEditOpen(true)} className="ml-auto bg-white"><Pencil className="mr-2 h-4 w-4" />Modifier</Button><Button onClick={() => setEventOpen(true)} className="bg-[#123653] hover:bg-[#0b2941]"><MessageSquarePlus className="mr-2 h-4 w-4" />Ajouter au journal</Button></>}</div>
    <div className="grid gap-5 xl:grid-cols-[1.1fr_.9fr]">
      <div className="space-y-5"><Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-lg">Demande</CardTitle></CardHeader><CardContent><p className="whitespace-pre-wrap text-sm leading-7 text-slate-700">{ticket.description || "Aucune description détaillée."}</p></CardContent></Card>
        <Card className="border-0 shadow-sm"><CardHeader className="flex-row items-center justify-between"><CardTitle className="text-lg">Journal du ticket</CardTitle><span className="text-xs text-muted-foreground">{events.length} événement{events.length > 1 ? "s" : ""}</span></CardHeader><CardContent><div className="relative space-y-5 before:absolute before:bottom-2 before:left-[7px] before:top-2 before:w-px before:bg-slate-200">{events.map(event => <div key={event.id} className="relative flex gap-4"><div className="relative z-10 mt-1 h-3.5 w-3.5 shrink-0 rounded-full border-2 border-white bg-teal-500 shadow" /><div className="min-w-0 flex-1 rounded-xl bg-slate-50 p-3"><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm font-semibold">{event.eventType}</p><p className="text-xs text-muted-foreground">{formatDate(event.createdAt, true)}</p></div><p className="mt-1 text-sm leading-6 text-slate-600">{event.content}</p><p className="mt-2 text-xs text-muted-foreground">{event.authorName || "Système"}</p></div></div>)}{!events.length && <p className="pl-7 text-sm text-muted-foreground">Aucun événement enregistré.</p>}</div></CardContent></Card>
      </div>
      <div className="space-y-5"><Card className="border-0 shadow-sm"><CardHeader><CardTitle className="flex items-center gap-2 text-lg"><Clock3 className="h-5 w-5 text-teal-700" />Délai de traitement</CardTitle></CardHeader><CardContent><div className={`rounded-2xl p-4 ${ticket.overdue ? "bg-rose-50 text-rose-800" : ticket.atRisk ? "bg-amber-50 text-amber-800" : "bg-emerald-50 text-emerald-800"}`}><p className="text-sm font-semibold">{ticket.label}</p><p className="mt-1 text-2xl font-semibold">{ticket.status === "Resolu" ? "Clôturé" : ticket.overdue ? `${Math.abs(ticket.remainingHours)} h` : `${ticket.remainingHours} h`}</p><p className="mt-1 text-xs">Échéance cible : {formatDate(ticket.target, true)}</p></div>{ticket.responseHours !== null && <p className="mt-4 text-sm text-muted-foreground">Première réponse en <strong className="text-slate-800">{ticket.responseHours} h</strong>.</p>}</CardContent></Card>
        <Card className="border-0 shadow-sm"><CardHeader><CardTitle className="text-lg">Responsabilité</CardTitle></CardHeader><CardContent className="space-y-4"><div className="flex items-center gap-3"><div className="rounded-lg bg-slate-100 p-2"><UserRound className="h-4 w-4" /></div><div><p className="text-xs text-muted-foreground">Assigné à</p><p className="text-sm font-medium">{ticket.assignedToName || "Non assigné"}</p></div></div><div className="flex items-center gap-3"><div className="rounded-lg bg-slate-100 p-2"><Building2 className="h-4 w-4" /></div><div><p className="text-xs text-muted-foreground">Établissement</p><p className="text-sm font-medium">{ticket.organizationName || "Interne"}</p></div></div><div className="flex items-center gap-3"><div className="rounded-lg bg-slate-100 p-2"><Headphones className="h-4 w-4" /></div><div><p className="text-xs text-muted-foreground">Ouvert le</p><p className="text-sm font-medium">{formatDate(ticket.createdAt, true)}</p></div></div></CardContent></Card>
        {canWrite && ticket.status !== "Resolu" && <Card className="border-0 bg-[#123653] text-white shadow-sm"><CardContent className="p-5"><CheckCircle2 className="mb-3 h-6 w-6 text-teal-300" /><p className="font-semibold">Faire avancer le ticket</p><p className="mt-1 text-sm text-slate-300">Mettez à jour son étape dès que le client ou l’équipe répond.</p><div className="mt-4 grid gap-2"><Button variant="secondary" onClick={() => changeStatus("En cours")}>Passer en cours</Button><Button variant="outline" className="border-white/20 text-white hover:bg-white/10" onClick={() => changeStatus("En attente client")}>En attente client</Button><Button className="bg-teal-500 text-white hover:bg-teal-600" onClick={() => changeStatus("Resolu")}>Marquer résolu</Button></div></CardContent></Card>}
      </div>
    </div>
    {editOpen && <TicketDialog key={ticket.updatedAt.toString()} open={editOpen} onOpenChange={setEditOpen} initial={ticket} />}
    {eventOpen && <TicketEventDialog open={eventOpen} onOpenChange={setEventOpen} ticketId={id} />}
  </div>;
}
